{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.4.2-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.4.2-pearson-offline.aar",
          "url": "flutter_release-1.4.2-pearson-offline.aar",
          "size": 10235504,
          "sha512": "7b961d607602c17b6f84d89cbc842c119fd99c816d60b62c9a368cb9c5f141883d7aa829093657eea3841871fd0716b61b52c4ff0c0adc0f2c37ae3e04a24581",
          "sha256": "4e29de91438411de3d9fdbec23b6e0124328617ccd4a8335f7e32c4f02a28ee2",
          "sha1": "ccb30bdf985bda6fabf4b82e0c829317aa112913",
          "md5": "54878a650dd3d5993940db5977ff4800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.4.2-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.4.2-pearson-offline.aar",
          "url": "flutter_release-1.4.2-pearson-offline.aar",
          "size": 10235504,
          "sha512": "7b961d607602c17b6f84d89cbc842c119fd99c816d60b62c9a368cb9c5f141883d7aa829093657eea3841871fd0716b61b52c4ff0c0adc0f2c37ae3e04a24581",
          "sha256": "4e29de91438411de3d9fdbec23b6e0124328617ccd4a8335f7e32c4f02a28ee2",
          "sha1": "ccb30bdf985bda6fabf4b82e0c829317aa112913",
          "md5": "54878a650dd3d5993940db5977ff4800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.4.2-pearson-offline-sources.jar",
          "url": "flutter_release-1.4.2-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.4.2-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.4.2-pearson-offline-javadoc.jar",
          "size": 261642,
          "sha512": "71631e4e7ebce2d2483d72a9f07f7e4e041faf26f1f9f5df4733cdab5ba26b0608189b0616636f1cfef1173231f3044925252592b3d01b82d9c6c49cc28cc57f",
          "sha256": "4d79efb5463481e6c6ece0a34cdc36727b8fc6261f6c3c138f42d3a94f3a08ff",
          "sha1": "1ba210339db38819351ca0d84d4b1edd7a3dc2f1",
          "md5": "9e2a09b0beef8e202224bddcf5f17e46"
        }
      ]
    }
  ]
}
