{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.4.1.aar",
          "url": "flutter_release-1.4.1.aar",
          "size": 8007196,
          "sha512": "0780823984173d4571177c7eed50d271872a87307c8e4fba0b9e847f120ce011f10dec1191d03eea82258a8222d8d82144f5aab980167f2e4c5ba64f8fea908b",
          "sha256": "326c5d884a98891646037fcafd0d680c535e94cc65d2a44181ab985d83276828",
          "sha1": "3fa6f1911468c4f20b93856730598574ae7b36a5",
          "md5": "5d5b2b14bc9fe6db4a5952364bf49520"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.4.1.aar",
          "url": "flutter_release-1.4.1.aar",
          "size": 8007196,
          "sha512": "0780823984173d4571177c7eed50d271872a87307c8e4fba0b9e847f120ce011f10dec1191d03eea82258a8222d8d82144f5aab980167f2e4c5ba64f8fea908b",
          "sha256": "326c5d884a98891646037fcafd0d680c535e94cc65d2a44181ab985d83276828",
          "sha1": "3fa6f1911468c4f20b93856730598574ae7b36a5",
          "md5": "5d5b2b14bc9fe6db4a5952364bf49520"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.4.1-sources.jar",
          "url": "flutter_release-1.4.1-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.4.1-javadoc.jar",
          "url": "flutter_release-1.4.1-javadoc.jar",
          "size": 261620,
          "sha512": "594ba315b0c63a7b5611be58b4cd70d3daf33692d182962b829d86bbb3f5129f63c44b83be63a8c86f2aec935d22d067261562768d10889b7936c844bb704a2f",
          "sha256": "1ce1b952ee100572ad138b6734e037db9d05b5f64d343708e002abf06e668c07",
          "sha1": "ab995b83723437b09156ad0d9af2b80580cb9e1f",
          "md5": "02482ef7aa563ed463e2940f94d8dc04"
        }
      ]
    }
  ]
}
