{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "1.5.6-sylvain",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain.aar",
          "size": 2475,
          "sha512": "2a97f528ede0b83142d9a25deec5aee1caa99369f73efed413e45a375b48da30f977529a7f791c5769ff6bd3d46fc3880fd3dfec37a8be717b0162eac5ab3021",
          "sha256": "b20912dd899945d34dfc865103237ee300540d47f84d53b94483445d5a8bdd07",
          "sha1": "9740738e61a2d5bf20c27f284c4d5616956deb40",
          "md5": "15d084c98b80c39477e9a3c6abb49f94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain.aar",
          "size": 2475,
          "sha512": "2a97f528ede0b83142d9a25deec5aee1caa99369f73efed413e45a375b48da30f977529a7f791c5769ff6bd3d46fc3880fd3dfec37a8be717b0162eac5ab3021",
          "sha256": "b20912dd899945d34dfc865103237ee300540d47f84d53b94483445d5a8bdd07",
          "sha1": "9740738e61a2d5bf20c27f284c4d5616956deb40",
          "md5": "15d084c98b80c39477e9a3c6abb49f94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain-sources.jar",
          "size": 2683,
          "sha512": "a3f7fee602ae01e1fe53ad82c914db15159744a75a0e4f439cdbe5e530abf6d3b431e26802ccd3cf08245278758e1aef335a9e00aec7ded1b1c89a60a53d7915",
          "sha256": "ea22384264efbced6ae1be61be8aadee870b81c3a1e0b6accc0ef62396aaeae0",
          "sha1": "1ddcac6e1149d882ff8719e00a4eebfeb282eb36",
          "md5": "351ed496e751473b57d20e3a693b432d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-1.5.6-sylvain-javadoc.jar",
          "size": 269850,
          "sha512": "813664264f36381e2d0b844e7750eb44fdd465667561adc4cb8cb1d4f69e4fe1640af101eaf81fa503e38df28412fcc09e98dc2a7ffe4f902abae71a09974418",
          "sha256": "2f594c040a7589f5f313197bebebf8a1ec42b5fdff102926c924477ecc7b8233",
          "sha1": "a3f9d621a9d84c64fcce529ebd02c0080140ba01",
          "md5": "adf38eac6bed3f4314bbe10bb79f0160"
        }
      ]
    }
  ]
}
