{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.3.9-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.3.9-offline.aar",
          "url": "palmid_sdk_flutter_release-1.3.9-offline.aar",
          "size": 34727747,
          "sha512": "fc9bc4499b24bc641a61e292871cd70b29fbb4c7b0836ad494a57292f7f0f52afe971081580e2b8064702d8c388b252b2ad2b4ce82d3b095a38d017f4bfc7677",
          "sha256": "e08259ffd84016297c748e5c99eb3b1db78f04f1c55be2cdb0b81d0b0ec30ef9",
          "sha1": "0dbcfa87ac54a0d838780e6e975ea0ff40dc8234",
          "md5": "4ab144d2950a848fd5c0899a9c589049"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.9-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.3.9-offline.aar",
          "url": "palmid_sdk_flutter_release-1.3.9-offline.aar",
          "size": 34727747,
          "sha512": "fc9bc4499b24bc641a61e292871cd70b29fbb4c7b0836ad494a57292f7f0f52afe971081580e2b8064702d8c388b252b2ad2b4ce82d3b095a38d017f4bfc7677",
          "sha256": "e08259ffd84016297c748e5c99eb3b1db78f04f1c55be2cdb0b81d0b0ec30ef9",
          "sha1": "0dbcfa87ac54a0d838780e6e975ea0ff40dc8234",
          "md5": "4ab144d2950a848fd5c0899a9c589049"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.3.9-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.3.9-offline-sources.jar",
          "size": 16978,
          "sha512": "ecede5f138ba3a708486cf20b16290128a16a03baf58413ef97766da253ed39a9dd47b713ea329baec6a93741e68da00de8a9847b06d611938a0a3771c316ad3",
          "sha256": "7bb0f69ae3098078f4af7cc1e19bfe433a989413834e1b1a7029c276bf595396",
          "sha1": "9a539c7bc004536f0caf292ffe8f39deb69747e2",
          "md5": "9b5a33e717945ec47d856c3e985fdddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.3.9-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.3.9-offline-javadoc.jar",
          "size": 423164,
          "sha512": "dbc818bad6428a0866168297a2b93712f709c0144842899c50a81e00f1e7ea5695b875eb6d08da055c9e249fa0ef95acce509c3cd799bb581e3df04ba02873ec",
          "sha256": "e17e9b249d8223f68d8f8bb4a96c45ec19cc04b0470ccfbf9df3026c4843f142",
          "sha1": "7d4eb52f6373738214cd3a7b8e6ef226412b3581",
          "md5": "b534fb19df8a16af99867a8032bafc41"
        }
      ]
    }
  ]
}
