{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.6.1-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.1-sylvain-offline.aar",
          "url": "flutter_release-1.6.1-sylvain-offline.aar",
          "size": 7465630,
          "sha512": "79c6e175e6add697e12ce9f713bd57dbc923c9ae0a48635491413a0ab6a139d8677a3eafffd9d2f31ad0a45a3be5ce2ff8d3c14b74186cd9021cc2e59322035a",
          "sha256": "5f46d87e7d210f753e195226f50c3311b57cb18994b636f45392ee404732c676",
          "sha1": "fd757f7c10a2f4ef4b9e2886c8c95db9b6f349e0",
          "md5": "96ee6354638e4a3ed2043c1e4c80aad0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.1-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.1-sylvain-offline.aar",
          "url": "flutter_release-1.6.1-sylvain-offline.aar",
          "size": 7465630,
          "sha512": "79c6e175e6add697e12ce9f713bd57dbc923c9ae0a48635491413a0ab6a139d8677a3eafffd9d2f31ad0a45a3be5ce2ff8d3c14b74186cd9021cc2e59322035a",
          "sha256": "5f46d87e7d210f753e195226f50c3311b57cb18994b636f45392ee404732c676",
          "sha1": "fd757f7c10a2f4ef4b9e2886c8c95db9b6f349e0",
          "md5": "96ee6354638e4a3ed2043c1e4c80aad0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.1-sylvain-offline-sources.jar",
          "url": "flutter_release-1.6.1-sylvain-offline-sources.jar",
          "size": 1275,
          "sha512": "516f87dd6a5f41d10cae19ec553a649d2d182948fa4abfe6cf3a6763e855478584ca0fafbc4d4f132e4db37daf10c4d50104a830bc6c9b52ef47b9e97e8b9d61",
          "sha256": "be211fcf47bd81e9c5d420622afc1edc0cc2fc57c5bee2db8b97a4d15ab6293a",
          "sha1": "edd41270e4541655faf517a8c892d859da0aa8d7",
          "md5": "0e5704b9e4fb4eec7d3557895b3be597"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.1-sylvain-offline-javadoc.jar",
          "url": "flutter_release-1.6.1-sylvain-offline-javadoc.jar",
          "size": 261644,
          "sha512": "62e0f79ba8a5683dbffe673b5364291b32bf747d6fe97384135b20e66be8246d4d3d8b008838a558d6f2d1b824f0653e914ed419cb69bbf062543b3141063590",
          "sha256": "cf526d2ff280c4d01207834b8061ba0be1b4e09a3de0b8f650096f75d665f522",
          "sha1": "ff9894b9429f9b0ccc68289583db6faa42b13431",
          "md5": "d36b9f15f69e5c69f8f29a4d6192a855"
        }
      ]
    }
  ]
}
