{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
    "module": "palmid_sdk_flutter_android_veinshine_release",
    "version": "1.6.11-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline.aar",
          "size": 16368615,
          "sha512": "b32a7794aa2d46eb6f0a1f33e1da25b3614b4a5957c404ed29fd2a08ca26866183aaad98d16f5afe0d8369bf7b8b1e104f15f08043bf5cf03a356ca243c09f0d",
          "sha256": "71c908ef522eb8bc3c261a30726cdfec0b48ba5aec4bb3f375f565e87a72fda4",
          "sha1": "1c185f85a1f9ecd860cf50c57ff5d12543d0d3b0",
          "md5": "6f0306f3bfd3af6e126dabb0a85b87f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline.aar",
          "size": 16368615,
          "sha512": "b32a7794aa2d46eb6f0a1f33e1da25b3614b4a5957c404ed29fd2a08ca26866183aaad98d16f5afe0d8369bf7b8b1e104f15f08043bf5cf03a356ca243c09f0d",
          "sha256": "71c908ef522eb8bc3c261a30726cdfec0b48ba5aec4bb3f375f565e87a72fda4",
          "sha1": "1c185f85a1f9ecd860cf50c57ff5d12543d0d3b0",
          "md5": "6f0306f3bfd3af6e126dabb0a85b87f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline-sources.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline-sources.jar",
          "size": 67323,
          "sha512": "881fcf4d1a8f4dced5f0ad295b79ed11cf254f3b967ad3e50feb867d6df5a163869abec0fa7c66b3ae5402a6f7461ce9266001e3f12185fdefbecdc746949572",
          "sha256": "e3c113a0b53d7c596a2e8d235472be95806d1420b675f9b3f1ebb514b5bdfafe",
          "sha1": "183fa4f3ccaecf7876a8a676fb79e63aa1a159b4",
          "md5": "b78adf685ac251a61a615577967da4e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.11-sylvain-offline-javadoc.jar",
          "size": 582703,
          "sha512": "cbc59cfb6f0699763e825ac80b15b7a3c639499f6e4a98ae64d437f6b36e4e2285cf1f6d731401e156dce9479f9d935df2e30ff9d43ebe447993f820622e6cd5",
          "sha256": "3f5af387d53807fb2e319ed26c324ddfc3cb7d76310feaea63bdb9fe1446cce0",
          "sha1": "303f4222daaa4aa441dc50f2694c0bf90c47a210",
          "md5": "144bce6f87bbe852ec1392cb4e0e4061"
        }
      ]
    }
  ]
}
