{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
    "module": "palmid_sdk_flutter_android_veinshine_release",
    "version": "1.6.5-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline.aar",
          "size": 16368615,
          "sha512": "b32a7794aa2d46eb6f0a1f33e1da25b3614b4a5957c404ed29fd2a08ca26866183aaad98d16f5afe0d8369bf7b8b1e104f15f08043bf5cf03a356ca243c09f0d",
          "sha256": "71c908ef522eb8bc3c261a30726cdfec0b48ba5aec4bb3f375f565e87a72fda4",
          "sha1": "1c185f85a1f9ecd860cf50c57ff5d12543d0d3b0",
          "md5": "6f0306f3bfd3af6e126dabb0a85b87f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline.aar",
          "size": 16368615,
          "sha512": "b32a7794aa2d46eb6f0a1f33e1da25b3614b4a5957c404ed29fd2a08ca26866183aaad98d16f5afe0d8369bf7b8b1e104f15f08043bf5cf03a356ca243c09f0d",
          "sha256": "71c908ef522eb8bc3c261a30726cdfec0b48ba5aec4bb3f375f565e87a72fda4",
          "sha1": "1c185f85a1f9ecd860cf50c57ff5d12543d0d3b0",
          "md5": "6f0306f3bfd3af6e126dabb0a85b87f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline-sources.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline-sources.jar",
          "size": 67323,
          "sha512": "881fcf4d1a8f4dced5f0ad295b79ed11cf254f3b967ad3e50feb867d6df5a163869abec0fa7c66b3ae5402a6f7461ce9266001e3f12185fdefbecdc746949572",
          "sha256": "e3c113a0b53d7c596a2e8d235472be95806d1420b675f9b3f1ebb514b5bdfafe",
          "sha1": "183fa4f3ccaecf7876a8a676fb79e63aa1a159b4",
          "md5": "b78adf685ac251a61a615577967da4e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.5-sylvain-offline-javadoc.jar",
          "size": 582657,
          "sha512": "8ce9138c0c7ed7eef4275752085b8ca5d49d1a0e5bed35af27393ed692a301a066509f8ae017ef6de12115fbbbd39ed6bf9ea44ed9875ebce325eadc572a850a",
          "sha256": "26747229c141d70d7bf04834e2644ebef6fbcbe4feacb87c36640e04c57ad51d",
          "sha1": "ed0fad715530dc860fde6a42be447a08739fd4b4",
          "md5": "5ec08248eac1bf77d6505492201d7900"
        }
      ]
    }
  ]
}
