{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.6.4-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.4-pearson-offline.aar",
          "url": "flutter_release-1.6.4-pearson-offline.aar",
          "size": 9126184,
          "sha512": "39f8f1a37f14451d9e32431b00b6796a5569028ff38e9bab1dcc32078ffae815d8973b8191fdc0e8154282fa3ebaace3936aed5483fb463fa79e9b34b559f71c",
          "sha256": "11034350d66a92f16cc1454112ba8a7c97efade542d9ded124c717370951da0c",
          "sha1": "09ef506b2057a234bf6a0dc6ff7a862a991cef3c",
          "md5": "73a81815c75bfc3e8187a8a8bcfef267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.4-pearson-offline.aar",
          "url": "flutter_release-1.6.4-pearson-offline.aar",
          "size": 9126184,
          "sha512": "39f8f1a37f14451d9e32431b00b6796a5569028ff38e9bab1dcc32078ffae815d8973b8191fdc0e8154282fa3ebaace3936aed5483fb463fa79e9b34b559f71c",
          "sha256": "11034350d66a92f16cc1454112ba8a7c97efade542d9ded124c717370951da0c",
          "sha1": "09ef506b2057a234bf6a0dc6ff7a862a991cef3c",
          "md5": "73a81815c75bfc3e8187a8a8bcfef267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.4-pearson-offline-sources.jar",
          "url": "flutter_release-1.6.4-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.4-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.6.4-pearson-offline-javadoc.jar",
          "size": 261644,
          "sha512": "9bb2872aa83cc56605e60e4f69380441dbe9511a2a2c4cbbe6eeebd09d4b25c9fe03d479b23bdc7729ea36e8bb05ba1d8e5fd60c01cff95dd5701aefcad6b4e3",
          "sha256": "5ff061d1b56442d577c81cc4962f949f49fd86bed0fb52decb99f377fcbe9cfa",
          "sha1": "93fe2b8c02a6b412ad3b5e912bee70d639d4ad9c",
          "md5": "b3b802e9b28dfb181e39bb50b6192335"
        }
      ]
    }
  ]
}
