{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
    "module": "palmid_sdk_flutter_android_veinshine_release",
    "version": "1.5.6-sylvain",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain.aar",
          "size": 15761516,
          "sha512": "6e890baee5f5db663f13d73ad5343ef8f1716fa15f747f525ca1acfa7ed38520a9c3664993b2241223cfbecc160da94719d8d4ec9bfbb01b7435712152f7b23c",
          "sha256": "a8346d5fcc2bfe800c4427975ebc663e9cc7a09d8ab05616f2795df4df513ec5",
          "sha1": "0d7e96e11555a613487c160d3b5a69582fde441d",
          "md5": "ce778837e41950507311509a128ec442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain.aar",
          "size": 15761516,
          "sha512": "6e890baee5f5db663f13d73ad5343ef8f1716fa15f747f525ca1acfa7ed38520a9c3664993b2241223cfbecc160da94719d8d4ec9bfbb01b7435712152f7b23c",
          "sha256": "a8346d5fcc2bfe800c4427975ebc663e9cc7a09d8ab05616f2795df4df513ec5",
          "sha1": "0d7e96e11555a613487c160d3b5a69582fde441d",
          "md5": "ce778837e41950507311509a128ec442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain-sources.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain-sources.jar",
          "size": 67323,
          "sha512": "881fcf4d1a8f4dced5f0ad295b79ed11cf254f3b967ad3e50feb867d6df5a163869abec0fa7c66b3ae5402a6f7461ce9266001e3f12185fdefbecdc746949572",
          "sha256": "e3c113a0b53d7c596a2e8d235472be95806d1420b675f9b3f1ebb514b5bdfafe",
          "sha1": "183fa4f3ccaecf7876a8a676fb79e63aa1a159b4",
          "md5": "b78adf685ac251a61a615577967da4e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain-javadoc.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.5.6-sylvain-javadoc.jar",
          "size": 582300,
          "sha512": "2dd8b0e5d3e0bfb3d495df58231ecb70f3d0db91b42046d023823d7189945685e5bc2a375c56546ebe6b453463dae0572f44c39cc7351790f7ecf62666fe3644",
          "sha256": "b27b5b2c720f179c30bf217ab61f28bcca37126d666adc927a008cc986d5c679",
          "sha1": "ae1d1dc28025f3fb3529dc714a949126f9daae53",
          "md5": "d1f20d39501d2db3ac4f9dc3025e8943"
        }
      ]
    }
  ]
}
