{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.1-pearson",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.1-pearson.aar",
          "url": "flutter_release-1.5.1-pearson.aar",
          "size": 10188223,
          "sha512": "437d64f8df118512475879ce58a8a02f5babe57fdcc55c45208c1481ed65dce31a5c37b785446ec4b9484a96c8823cafd0663af0c5d1bb199905c76bb0bacbc1",
          "sha256": "5b14b245aca037d7a2fbf7717fb20f1b9c6da346830915afddffa7b363b42868",
          "sha1": "2320d12b6c46e42278ffa09882777560bc3f3aaa",
          "md5": "99bc3089d72b1204f7b5b3936274ac9b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.1-pearson.aar",
          "url": "flutter_release-1.5.1-pearson.aar",
          "size": 10188223,
          "sha512": "437d64f8df118512475879ce58a8a02f5babe57fdcc55c45208c1481ed65dce31a5c37b785446ec4b9484a96c8823cafd0663af0c5d1bb199905c76bb0bacbc1",
          "sha256": "5b14b245aca037d7a2fbf7717fb20f1b9c6da346830915afddffa7b363b42868",
          "sha1": "2320d12b6c46e42278ffa09882777560bc3f3aaa",
          "md5": "99bc3089d72b1204f7b5b3936274ac9b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.1-pearson-sources.jar",
          "url": "flutter_release-1.5.1-pearson-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.1-pearson-javadoc.jar",
          "url": "flutter_release-1.5.1-pearson-javadoc.jar",
          "size": 261631,
          "sha512": "51f483d906c7eeae65b6972295790584a0b1f5a797eb35806a61feeea68cf9d55d41319165140b3ea0a5a43dbe9abb6fc3dd5c13b517fe3963fcc9578e23c74c",
          "sha256": "25520283059e7a8f8f9dce9e4cf0e87e0d4c054e4d6595f49d522eba23e2a6e5",
          "sha1": "f3db2e0f271aa92c1fd8396cd577f1af2fe37a0f",
          "md5": "e48c5f4fb3ac18acc476811fef99b698"
        }
      ]
    }
  ]
}
