{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.3.aar",
          "url": "flutter_release-1.3.3.aar",
          "size": 6879520,
          "sha512": "39f9c1372b656a99b2993348b6ec49da1c3847ac6da11d103d2e5856e0ee4ea444348068701bcadaf607f4496361574de246312fb3c0a62c4a20f6f24f0c6a0b",
          "sha256": "140ff5d3c23e219593bf5aa342a0919194e2f1b5bcf4ef176dc7e4304ed584eb",
          "sha1": "0a4e381de66aeda52138ac88558bb05b9a59e265",
          "md5": "7b31d534e34ac4ef958c2446cd131a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.3.aar",
          "url": "flutter_release-1.3.3.aar",
          "size": 6879520,
          "sha512": "39f9c1372b656a99b2993348b6ec49da1c3847ac6da11d103d2e5856e0ee4ea444348068701bcadaf607f4496361574de246312fb3c0a62c4a20f6f24f0c6a0b",
          "sha256": "140ff5d3c23e219593bf5aa342a0919194e2f1b5bcf4ef176dc7e4304ed584eb",
          "sha1": "0a4e381de66aeda52138ac88558bb05b9a59e265",
          "md5": "7b31d534e34ac4ef958c2446cd131a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.3-sources.jar",
          "url": "flutter_release-1.3.3-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.3-javadoc.jar",
          "url": "flutter_release-1.3.3-javadoc.jar",
          "size": 261617,
          "sha512": "5029784a7a1fc77dc06b3fb07ca9effb8defe1e82225b24c1a6c53f70b785265b004a04668a290fd03f079e74107913c53b571357a4e56cd1b96aee78fc66228",
          "sha256": "9b7dbcce9c8f76fd87974f6fe91cce385e2d228dfb60520253e9084b889d64c9",
          "sha1": "d3e48bdeb3b14ac38d97af308a6e45fb72b72313",
          "md5": "c7384f51a505d56695a896825bad1316"
        }
      ]
    }
  ]
}
