{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7.aar",
          "url": "palmid_sdk_flutter_release-1.5.7.aar",
          "size": 34871492,
          "sha512": "a09a894123b29f19211699a10e943a850ad2da9174b47a49e6657924b6cc302a724e31afc837c3f982c1bb7dd13420746f6f41cfb889c048b11b945522a9355c",
          "sha256": "12787f43376c2038266acb4a76b5bd04643a5627662fd55d1f2d4d8712cbd177",
          "sha1": "ba87cc2ac0b0d9d271ef8380ca91fbf51fec8fb5",
          "md5": "e07cb000b462f0e8482dc26a38431050"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7.aar",
          "url": "palmid_sdk_flutter_release-1.5.7.aar",
          "size": 34871492,
          "sha512": "a09a894123b29f19211699a10e943a850ad2da9174b47a49e6657924b6cc302a724e31afc837c3f982c1bb7dd13420746f6f41cfb889c048b11b945522a9355c",
          "sha256": "12787f43376c2038266acb4a76b5bd04643a5627662fd55d1f2d4d8712cbd177",
          "sha1": "ba87cc2ac0b0d9d271ef8380ca91fbf51fec8fb5",
          "md5": "e07cb000b462f0e8482dc26a38431050"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.7-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.7-javadoc.jar",
          "size": 423094,
          "sha512": "b3ae46e30c945ff587ccf1a258568e76cf6438d90a841d62d4b2736b05957fc107261cb0e0f35e291501c516fbdea221f8eae4bd05f95f389082e0711b7c0873",
          "sha256": "856c54424acbdf5f377006b948651f0f874edf071b0ab918d34bf0f2e96dd238",
          "sha1": "aa5abd197e82d0bdea379aee0216d8556f4c473f",
          "md5": "9a6737affb6381d93b169efe8708dca5"
        }
      ]
    }
  ]
}
