{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.8.0-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0-pearson-offline.aar",
          "url": "flutter_release-1.8.0-pearson-offline.aar",
          "size": 9121374,
          "sha512": "6b19b416c8a68b8d346f3b62e6d2b9e8a887059e31ccc7c57b7f4d7044281f3b167deb37ab162785dec6038d8bcb3b5537f50e9fadd79cec20a587e95f09ced2",
          "sha256": "27bc8fc4e1dac6fdf7c75762ea186c550f7f7120b69c238530fbaab92a58dc83",
          "sha1": "d17ea89656b71041f53c33f80c9707fe5d17d287",
          "md5": "b592cd3732e858b5546ba5b005735072"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0-pearson-offline.aar",
          "url": "flutter_release-1.8.0-pearson-offline.aar",
          "size": 9121374,
          "sha512": "6b19b416c8a68b8d346f3b62e6d2b9e8a887059e31ccc7c57b7f4d7044281f3b167deb37ab162785dec6038d8bcb3b5537f50e9fadd79cec20a587e95f09ced2",
          "sha256": "27bc8fc4e1dac6fdf7c75762ea186c550f7f7120b69c238530fbaab92a58dc83",
          "sha1": "d17ea89656b71041f53c33f80c9707fe5d17d287",
          "md5": "b592cd3732e858b5546ba5b005735072"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.8.0-pearson-offline-sources.jar",
          "url": "flutter_release-1.8.0-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.8.0-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.8.0-pearson-offline-javadoc.jar",
          "size": 261642,
          "sha512": "f17a8bfe6d9fa8dadd1451a82516970a0141ed2060b6454d609ed5736e5144394f960cf5b207be901514ff60b3d873876a63701562c29ad58bd1c7615629dfdf",
          "sha256": "c4805df9f68adcc14126c7bb1d69b1215296c771a4ea4fa52c6214cbaa5d929c",
          "sha1": "9311952b71e3c460c05d004636a413e831cfff6b",
          "md5": "ed2d72672b12dba13740a4a7b5b6baf7"
        }
      ]
    }
  ]
}
