{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.5.3.aar",
          "url": "device_info_plus_release-1.5.3.aar",
          "size": 7080,
          "sha512": "d90496a2f7ec5aba017e657b80f3d472a699b5c52061b21206bbbdfc38b1a5c38e4f5e93f9e3ebb8f50dc88c297534d552e0ca72a68c913617b5af0d918326a8",
          "sha256": "c6df09b8817146d654326f8bc04e8d6395ec7dc656c829df67527aa6cb2c50fd",
          "sha1": "d654eb2dc5457a1693b58817b33e94b22a1f6daa",
          "md5": "339d73ee960f7ce622c0e183b487cb7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.5.3.aar",
          "url": "device_info_plus_release-1.5.3.aar",
          "size": 7080,
          "sha512": "d90496a2f7ec5aba017e657b80f3d472a699b5c52061b21206bbbdfc38b1a5c38e4f5e93f9e3ebb8f50dc88c297534d552e0ca72a68c913617b5af0d918326a8",
          "sha256": "c6df09b8817146d654326f8bc04e8d6395ec7dc656c829df67527aa6cb2c50fd",
          "sha1": "d654eb2dc5457a1693b58817b33e94b22a1f6daa",
          "md5": "339d73ee960f7ce622c0e183b487cb7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.5.3-sources.jar",
          "url": "device_info_plus_release-1.5.3-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.5.3-javadoc.jar",
          "url": "device_info_plus_release-1.5.3-javadoc.jar",
          "size": 260827,
          "sha512": "654a3db4dcea35f65b775e3f91b3e4d44d2a80f853d4f6b5620275e67eb728fb0379bbd200225cb20bed20fd4ac8bdfd7164dfd02ed98edcf272a5c62d681ef9",
          "sha256": "8c5fbab3549cb408f410d55bcf5c9e205e591670067a108ba69e59d4312867ea",
          "sha1": "b3f151064cf192c67e00b331ad1fa43156147763",
          "md5": "0f868650192aeb0048870af47cb7d654"
        }
      ]
    }
  ]
}
