{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.3.6-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.6-offline.aar",
          "url": "flutter_release-1.3.6-offline.aar",
          "size": 6746697,
          "sha512": "10eea120bcc78deae891e4278ea331a1fc56501e114e429b8509382fef3eb1f68f683502182e8705f9ed4751de229a5d85542184a387f1893a0df245635918a9",
          "sha256": "79bf35843a589468685c2058d42ff1fe2900720a2cb48b2b6713a2ed2614bad6",
          "sha1": "39612f8dba051051cd1adde51a7ad0456ffa7788",
          "md5": "02d2507c31a23edf95b75a70f6f34aaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.6-offline.aar",
          "url": "flutter_release-1.3.6-offline.aar",
          "size": 6746697,
          "sha512": "10eea120bcc78deae891e4278ea331a1fc56501e114e429b8509382fef3eb1f68f683502182e8705f9ed4751de229a5d85542184a387f1893a0df245635918a9",
          "sha256": "79bf35843a589468685c2058d42ff1fe2900720a2cb48b2b6713a2ed2614bad6",
          "sha1": "39612f8dba051051cd1adde51a7ad0456ffa7788",
          "md5": "02d2507c31a23edf95b75a70f6f34aaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.6-offline-sources.jar",
          "url": "flutter_release-1.3.6-offline-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.6-offline-javadoc.jar",
          "url": "flutter_release-1.3.6-offline-javadoc.jar",
          "size": 261631,
          "sha512": "7f25ea665a6f529062e856b36a17792ff05afb89e370c15cee26088ab86cff8cdd5be8e902ecc0373fdc0a1533a14af457e7e29b1e14432c0bbd980f4280a470",
          "sha256": "299f29f7dd692cceb44e98ab5cbb7d9d5f85e06cd77c5f2b8867cd414d0ce452",
          "sha1": "366984b0171628d34f24c3ff17b2a4799b8c3424",
          "md5": "4c4a02c84e3e428b8eb7c76cb0d52556"
        }
      ]
    }
  ]
}
