{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.8-sylvain",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.8-sylvain.aar",
          "url": "flutter_release-1.5.8-sylvain.aar",
          "size": 7459150,
          "sha512": "e03e475bb0d7ab0f3fc0ecb4c748ed19cdac395fdc76051cee1049a9aaf41988b889f90c5c7a89eb548d12abe4486b19a90eeb3edab328faecbc3ee8ec31f1b0",
          "sha256": "338539ef4b3d74314485801a8d6a084651eb82126767b8062bf3c57836500b1e",
          "sha1": "b020782fac44765297500ee00437844937f72288",
          "md5": "33e2013b9d4f87f692ced183c8b6f71b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.8-sylvain"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.8-sylvain.aar",
          "url": "flutter_release-1.5.8-sylvain.aar",
          "size": 7459150,
          "sha512": "e03e475bb0d7ab0f3fc0ecb4c748ed19cdac395fdc76051cee1049a9aaf41988b889f90c5c7a89eb548d12abe4486b19a90eeb3edab328faecbc3ee8ec31f1b0",
          "sha256": "338539ef4b3d74314485801a8d6a084651eb82126767b8062bf3c57836500b1e",
          "sha1": "b020782fac44765297500ee00437844937f72288",
          "md5": "33e2013b9d4f87f692ced183c8b6f71b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.8-sylvain-sources.jar",
          "url": "flutter_release-1.5.8-sylvain-sources.jar",
          "size": 1275,
          "sha512": "516f87dd6a5f41d10cae19ec553a649d2d182948fa4abfe6cf3a6763e855478584ca0fafbc4d4f132e4db37daf10c4d50104a830bc6c9b52ef47b9e97e8b9d61",
          "sha256": "be211fcf47bd81e9c5d420622afc1edc0cc2fc57c5bee2db8b97a4d15ab6293a",
          "sha1": "edd41270e4541655faf517a8c892d859da0aa8d7",
          "md5": "0e5704b9e4fb4eec7d3557895b3be597"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.8-sylvain-javadoc.jar",
          "url": "flutter_release-1.5.8-sylvain-javadoc.jar",
          "size": 261633,
          "sha512": "7826ebb33dc09cc8e09e3855046e15a599cdb14fd1bad0ec616200512ea1614b42f91aa6b8ea94dad8866d7341944a989623d02bd132a88bf2ae949fcf82761d",
          "sha256": "5649aff73024062a738018c9bb31d1c66f4df97e6fe278be03e112f7b8a03377",
          "sha1": "0d1feb1b168e157879d1f65f1fc75f478354391f",
          "md5": "a685fe229470b9fcd0305388854a3f5d"
        }
      ]
    }
  ]
}
