{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.7.0-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.0-offline.aar",
          "url": "flutter_release-1.7.0-offline.aar",
          "size": 8015946,
          "sha512": "e25c91813af6b44dd7448eb6d48282cf58e688f5264a426d033031fdfeaea92499e3821c56aa7981d202c37a3f41fba1b14426c99579f3dfbc6110be1aaf4998",
          "sha256": "0f2f5af325b2b4fcd08d15d6386ee9995c799889ae8e1af0968e1fbb97af380b",
          "sha1": "dc2fb08c86af27f4431944eb151f24d181202d33",
          "md5": "55632b8970251d5897bc57c498a08c1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.7.0-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.0-offline.aar",
          "url": "flutter_release-1.7.0-offline.aar",
          "size": 8015946,
          "sha512": "e25c91813af6b44dd7448eb6d48282cf58e688f5264a426d033031fdfeaea92499e3821c56aa7981d202c37a3f41fba1b14426c99579f3dfbc6110be1aaf4998",
          "sha256": "0f2f5af325b2b4fcd08d15d6386ee9995c799889ae8e1af0968e1fbb97af380b",
          "sha1": "dc2fb08c86af27f4431944eb151f24d181202d33",
          "md5": "55632b8970251d5897bc57c498a08c1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.7.0-offline-sources.jar",
          "url": "flutter_release-1.7.0-offline-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.7.0-offline-javadoc.jar",
          "url": "flutter_release-1.7.0-offline-javadoc.jar",
          "size": 261631,
          "sha512": "3f831b3e9e68095faa30f02d29bbfc920ceda375f33d66878762f08f7ef23234dd0742d5343c1eaee345b29e1bcc687c6a334bfd74bcad26c69df19825b14d81",
          "sha256": "3f5ea81d1641d94815582deb0a6a4ce4a2664261ff7e78c32c3ed7113e3844a1",
          "sha1": "2b377c05bfa9e60a6964ad26568ab3bb99feb232",
          "md5": "34be002e63a315462f2c5915385f2215"
        }
      ]
    }
  ]
}
