{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.6.4-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.4-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.6.4-pearson-offline.aar",
          "size": 35429310,
          "sha512": "4dad2bf64d3550ad738153a211c40943ba760074c3881cc125e880c901610a757a7f85a5ae65d0b10d95c5cb236dcb78351ce189a0838786fb2fcf19f8baa8e8",
          "sha256": "52cd3fa59d63fa6f23e9d6991509f48c7e65d044974e0a0eed7a2579d62d45ba",
          "sha1": "ee75c5c19ae4d136f074d3b4dd09b5f1c12bed64",
          "md5": "adf14672345daa24450e73aa255fde1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.4-pearson-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.4-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.6.4-pearson-offline.aar",
          "size": 35429310,
          "sha512": "4dad2bf64d3550ad738153a211c40943ba760074c3881cc125e880c901610a757a7f85a5ae65d0b10d95c5cb236dcb78351ce189a0838786fb2fcf19f8baa8e8",
          "sha256": "52cd3fa59d63fa6f23e9d6991509f48c7e65d044974e0a0eed7a2579d62d45ba",
          "sha1": "ee75c5c19ae4d136f074d3b4dd09b5f1c12bed64",
          "md5": "adf14672345daa24450e73aa255fde1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.4-pearson-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.6.4-pearson-offline-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.4-pearson-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.6.4-pearson-offline-javadoc.jar",
          "size": 423655,
          "sha512": "d7484824747ed9e0550c3e7f43ae1c1ee0aa841dd161f8e7a9dc2296558f7e8fd768fcb112e330b7887894f9fd2aae7de8e14ed355913308fa1f49c6fe5ca94f",
          "sha256": "22e3bdd80970186ac3b482e5ce2807879ebb01ecf3d47901cc438d11df63893a",
          "sha1": "dc7c0c51c2d4aab250c840cda34567a0d9482824",
          "md5": "ede469fd6186b50d4b1c00a74871e6b5"
        }
      ]
    }
  ]
}
