{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.6.aar",
          "url": "flutter_release-1.5.6.aar",
          "size": 8015109,
          "sha512": "e6c1841a7fb3114354aace6669c672e2147e200e17e4cc74d0d4fea0405a45d46d6885c6d4d6b42d857817974d645e3f113f3f622e543c208a4df0e915e565cf",
          "sha256": "215df41bea9778a7290b5f6fe41b7adb8cdb013a7349040d4e6d0a49a8724df3",
          "sha1": "e73030edb9d5933c0fb92a71cdb45852f4b65d74",
          "md5": "f3a3e0ccec33bd423b84a7305acfd68c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.6.aar",
          "url": "flutter_release-1.5.6.aar",
          "size": 8015109,
          "sha512": "e6c1841a7fb3114354aace6669c672e2147e200e17e4cc74d0d4fea0405a45d46d6885c6d4d6b42d857817974d645e3f113f3f622e543c208a4df0e915e565cf",
          "sha256": "215df41bea9778a7290b5f6fe41b7adb8cdb013a7349040d4e6d0a49a8724df3",
          "sha1": "e73030edb9d5933c0fb92a71cdb45852f4b65d74",
          "md5": "f3a3e0ccec33bd423b84a7305acfd68c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.6-sources.jar",
          "url": "flutter_release-1.5.6-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.6-javadoc.jar",
          "url": "flutter_release-1.5.6-javadoc.jar",
          "size": 261621,
          "sha512": "2d6a1ef2b115ddfb1c33a177a7f60c9988cdc8ae49d8476e5fbd36837096654a6aed3b3778299c1e5fb1b6559dd0e2c968654b3fd545c5acc21c9ace437c6cc2",
          "sha256": "65feda30eaef3186771e7598fdac71c99feb68a062978a3b3e4711b7bf11fcc4",
          "sha1": "d84a3567879e3864a2653c466c03029574f9c00b",
          "md5": "6619df0e2ea92fc33bf82b268ba28f8d"
        }
      ]
    }
  ]
}
