{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.8.aar",
          "url": "flutter_release-1.3.8.aar",
          "size": 8008419,
          "sha512": "0dd8fbb47caab4b27ccfa298f1e82f9edb3d162e2984ded47ccc03e229c064685c01248fbfe8f566478c8f5c79de0b4c5c246ef4fda80a5ec0d71579199e4ac8",
          "sha256": "9f4fd5a663620ba78a64f279ca192c2a2c6c1f5e95b8a158220ffbc646048a8e",
          "sha1": "86c26fcd82deacba9a878730378fcc72192a4e77",
          "md5": "e486de2cf946ae528669bcc8f389b087"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.8.aar",
          "url": "flutter_release-1.3.8.aar",
          "size": 8008419,
          "sha512": "0dd8fbb47caab4b27ccfa298f1e82f9edb3d162e2984ded47ccc03e229c064685c01248fbfe8f566478c8f5c79de0b4c5c246ef4fda80a5ec0d71579199e4ac8",
          "sha256": "9f4fd5a663620ba78a64f279ca192c2a2c6c1f5e95b8a158220ffbc646048a8e",
          "sha1": "86c26fcd82deacba9a878730378fcc72192a4e77",
          "md5": "e486de2cf946ae528669bcc8f389b087"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.8-sources.jar",
          "url": "flutter_release-1.3.8-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.8-javadoc.jar",
          "url": "flutter_release-1.3.8-javadoc.jar",
          "size": 261618,
          "sha512": "2f22a6db40d351978f8234a4335a5746aea4edfa39beae8e168dfc8d45e4491f10d5190c41f1541aae8f1c15615d9133e7cc19eb6b7339f9beb360585ee3df14",
          "sha256": "ee24f392f05f73cf1c1cc8d5802cc0bf9d72b045a0ef3f21176438ada981ec0a",
          "sha1": "f21a1fc1b8ffbc74bc37930bd95284ff924b77a4",
          "md5": "cf3e6ac57307289792e62696c29f0726"
        }
      ]
    }
  ]
}
