{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.sensors",
    "module": "sensors_plus_release",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-1.5.0.aar",
          "url": "sensors_plus_release-1.5.0.aar",
          "size": 9126,
          "sha512": "4386553cd3696ff30a9be013d9d200c401ea798e9e88977d4d756defd4910a5a91384e1c241fe8dbe1fb1545ff62a41b58ff542140d7f843fb3df57a8997428d",
          "sha256": "8987962254be4d8e4011f551f1120dad668a07538f1f0929e738fac73dc08b34",
          "sha1": "f79cbba473849ac57e2bffec7af8b6399996cb54",
          "md5": "23dd11d7eaff8d30039726f927b4148e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-1.5.0.aar",
          "url": "sensors_plus_release-1.5.0.aar",
          "size": 9126,
          "sha512": "4386553cd3696ff30a9be013d9d200c401ea798e9e88977d4d756defd4910a5a91384e1c241fe8dbe1fb1545ff62a41b58ff542140d7f843fb3df57a8997428d",
          "sha256": "8987962254be4d8e4011f551f1120dad668a07538f1f0929e738fac73dc08b34",
          "sha1": "f79cbba473849ac57e2bffec7af8b6399996cb54",
          "md5": "23dd11d7eaff8d30039726f927b4148e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-1.5.0-sources.jar",
          "url": "sensors_plus_release-1.5.0-sources.jar",
          "size": 3078,
          "sha512": "ff8c14ac129b7e7d57ba1c1d48a7bd51656b3a77eccd557666bdf8a3b0172ecca0df5ba81b9ebbe8d029f941c22d8f18a241481915f11253f61492bda395d5e3",
          "sha256": "bc48e760fb87da67a364f00faddba3a1e477beac55f4ede297734f50cf1cd795",
          "sha1": "6b5cb27f9ac4f036dc8728014deb48440cb4dfba",
          "md5": "19db92f4ba177bdc11b351b78aa144de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-1.5.0-javadoc.jar",
          "url": "sensors_plus_release-1.5.0-javadoc.jar",
          "size": 264701,
          "sha512": "f37cc862d53b48ccaed2608f76f438e4eed3700fc8bb2596deaa83b9c17a2e7469ec6e5f7652c9580e8f0d4ba8322cd93e27c3da26475a7ce399b3bc70d117a9",
          "sha256": "a4a737fbba8776b9d3e9ffd41febe5ea69bbbc8ef31fb7de376201f0f5319b7c",
          "sha1": "a9e0de56274ff459168dc8a75e0f93110e784d1e",
          "md5": "f52872e0f775c91cf0a2ef19e1b2dafe"
        }
      ]
    }
  ]
}
