{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid",
    "module": "native_sdk",
    "version": "1.5.6-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.5.6-pearson-offline.aar",
          "url": "native_sdk-1.5.6-pearson-offline.aar",
          "size": 12284,
          "sha512": "5a47411fcd48dae6a3991069afe776c0cf82079d2ac773b242b8c906bd84d667b223f9e35f3bd910d66b15c5050c14ddb31c1a105bf6e7227c6612b81e2ac190",
          "sha256": "29b33730226b6d6df7764bea9bc2532e121051c3243377b93de19da0478a610f",
          "sha1": "436431e87fae57ab231f7c15bc101723ee9c99c3",
          "md5": "4962367b0cde4e815daa7dad0a04c450"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.5.6-pearson-offline.aar",
          "url": "native_sdk-1.5.6-pearson-offline.aar",
          "size": 12284,
          "sha512": "5a47411fcd48dae6a3991069afe776c0cf82079d2ac773b242b8c906bd84d667b223f9e35f3bd910d66b15c5050c14ddb31c1a105bf6e7227c6612b81e2ac190",
          "sha256": "29b33730226b6d6df7764bea9bc2532e121051c3243377b93de19da0478a610f",
          "sha1": "436431e87fae57ab231f7c15bc101723ee9c99c3",
          "md5": "4962367b0cde4e815daa7dad0a04c450"
        }
      ]
    }
  ]
}
