{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.1-pearson",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson.aar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson.aar",
          "size": 34870987,
          "sha512": "d1f33d7faaa850c0ceb1c06ddc552da425e755fc76ff91e2aabe0ee276e92c385ba96605a52210a6280514d2c6cba8942954d6bfdc807089570fd3e5ac5ba3eb",
          "sha256": "fdd2fabc7a6c1e33074fbcbf3a0b7c1b62d01067b6430e6bf487a0bf9dab88ad",
          "sha1": "958d2f2678cfffc78c4603cf2951899312eefda8",
          "md5": "e001aa9f585f8b023b1a03cdd7596cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.1-pearson"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson.aar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson.aar",
          "size": 34870987,
          "sha512": "d1f33d7faaa850c0ceb1c06ddc552da425e755fc76ff91e2aabe0ee276e92c385ba96605a52210a6280514d2c6cba8942954d6bfdc807089570fd3e5ac5ba3eb",
          "sha256": "fdd2fabc7a6c1e33074fbcbf3a0b7c1b62d01067b6430e6bf487a0bf9dab88ad",
          "sha1": "958d2f2678cfffc78c4603cf2951899312eefda8",
          "md5": "e001aa9f585f8b023b1a03cdd7596cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-sources.jar",
          "size": 17149,
          "sha512": "c097e9f9245cb64921f3c62f487b469ff0367e13d8122f72aa90d9deafcc4977899884bcba37afa25aef0b771434cebc43f59f5b9f439aa0bbb3e428cc3d107a",
          "sha256": "b601253edc8ea544603e33119650b38e8264a53ac3ff240718a81b92c5e08081",
          "sha1": "fd57504702462da7d451ad9181c7ad3df5f330cf",
          "md5": "b4356bd794cdbc5a358a67e0f2e4436e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-javadoc.jar",
          "size": 423289,
          "sha512": "2b8ecd4c1a711fd4435233bbe6309b3d4afb17de332a623fd8de06b302a35c1b6e46f474c2722fe840e9c60f2167f719a1e07bc76cb2f34b614c2df98c430143",
          "sha256": "d97b1ff80794e45acc4ebc49c7f7f20a25ba1e79d271c77afa4576c65fde9bfe",
          "sha1": "815e4deef83bdb10bbff3c7b234361a99670caed",
          "md5": "1b3f835af15f4a636b1371c809b2fd71"
        }
      ]
    }
  ]
}
