{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.0.aar",
          "url": "flutter_release-1.1.0.aar",
          "size": 6330769,
          "sha512": "9842a0d98b77022f5f88e7fc067342c371d2a6af00df3ff5c5a85bcaf2597f7a69e5824b40bf55c92660f31f9ee58da6b96f24e665d59dbb80b1817ed2e8cd2c",
          "sha256": "3d8fd0c9eb8b74650f298534e1f173919a0e6ed5b21a6fcfff0a179f66614ffa",
          "sha1": "8a96fff8d3e6c2121f4d68e12d517242a108c42c",
          "md5": "d7b5f24bd2b9493585cc563962a5b379"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.0.aar",
          "url": "flutter_release-1.1.0.aar",
          "size": 6330769,
          "sha512": "9842a0d98b77022f5f88e7fc067342c371d2a6af00df3ff5c5a85bcaf2597f7a69e5824b40bf55c92660f31f9ee58da6b96f24e665d59dbb80b1817ed2e8cd2c",
          "sha256": "3d8fd0c9eb8b74650f298534e1f173919a0e6ed5b21a6fcfff0a179f66614ffa",
          "sha1": "8a96fff8d3e6c2121f4d68e12d517242a108c42c",
          "md5": "d7b5f24bd2b9493585cc563962a5b379"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.0-sources.jar",
          "url": "flutter_release-1.1.0-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.0-javadoc.jar",
          "url": "flutter_release-1.1.0-javadoc.jar",
          "size": 261619,
          "sha512": "9207b04bb91fa30f486b30bc1f72925f873ec3a2468066687f3f97f0e0e342873e10dde2bebc36ad5e842f609e5a4c3d08d97fd3b8e8cac6aed105923aaa72d5",
          "sha256": "7be3289bd965593104d8bfd55c86d289dc3f4d5068f70366450b237ba98065cf",
          "sha1": "bf55dc10e20c9601ffa0032434a117a566325fe7",
          "md5": "8e7f3af85874be1878560c9ea1e2cc1a"
        }
      ]
    }
  ]
}
