{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.1.aar",
          "url": "palmid_sdk_flutter_release-1.6.1.aar",
          "size": 35429338,
          "sha512": "b845483c88492eb0ae8059d0dcce9faf35babd8ebd1e722c7fd2961342a6020898393c7258e9d2d5083872a7ebef3cc3ac7122632158349394c3fba09ea08797",
          "sha256": "c767ca32906d48534455af8e0c2193470f3b45137299e945960b981dd999afa9",
          "sha1": "e88c64088b1c10c6dc3ebb7d6dbe135c10d1f596",
          "md5": "0f17fc1238f25ecc5330e206d3759829"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.1.aar",
          "url": "palmid_sdk_flutter_release-1.6.1.aar",
          "size": 35429338,
          "sha512": "b845483c88492eb0ae8059d0dcce9faf35babd8ebd1e722c7fd2961342a6020898393c7258e9d2d5083872a7ebef3cc3ac7122632158349394c3fba09ea08797",
          "sha256": "c767ca32906d48534455af8e0c2193470f3b45137299e945960b981dd999afa9",
          "sha1": "e88c64088b1c10c6dc3ebb7d6dbe135c10d1f596",
          "md5": "0f17fc1238f25ecc5330e206d3759829"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.1-sources.jar",
          "url": "palmid_sdk_flutter_release-1.6.1-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.6.1-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.6.1-javadoc.jar",
          "size": 423079,
          "sha512": "f597d157b2e08656db1d80e2bee2c7e57fba3658fc79058a13cb3ebe263de08b47489b83f5dad59047bcfe10e154bcfb46636d75772a7b2dc10ae8d577d58f5d",
          "sha256": "4a604d18de09ed53fa7ab5037bf4ceed5ba0d8283c3a4b197b1552757b621a4e",
          "sha1": "3fbc06ed5448b8f6b7699300ec61976f61161994",
          "md5": "5d5504b0e778065e5d11c1ce54434f3e"
        }
      ]
    }
  ]
}
