{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.4.0-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.4.0-offline.aar",
          "url": "permission_handler_android_release-1.4.0-offline.aar",
          "size": 24887,
          "sha512": "535b0a57dd53db7fbf176bbb324c9ae422138039b40c45df1d8332bd3aeab8f5d677703f82250ec256f1bb69334e8f9a6222db04dd4304b8eab2fb77d7e0fa6f",
          "sha256": "6cf135bc253460d388a4f3b71f29d9b384ac22ec2610295186443bdb13db7629",
          "sha1": "fa27d2778c082d108c88a33365142725bab77d7e",
          "md5": "26667cd96c3283a50833e321034efe2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.4.0-offline.aar",
          "url": "permission_handler_android_release-1.4.0-offline.aar",
          "size": 24887,
          "sha512": "535b0a57dd53db7fbf176bbb324c9ae422138039b40c45df1d8332bd3aeab8f5d677703f82250ec256f1bb69334e8f9a6222db04dd4304b8eab2fb77d7e0fa6f",
          "sha256": "6cf135bc253460d388a4f3b71f29d9b384ac22ec2610295186443bdb13db7629",
          "sha1": "fa27d2778c082d108c88a33365142725bab77d7e",
          "md5": "26667cd96c3283a50833e321034efe2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-1.4.0-offline-sources.jar",
          "url": "permission_handler_android_release-1.4.0-offline-sources.jar",
          "size": 16639,
          "sha512": "b3a678635b18a2f371405ea4b62ce0ce4661f3fe7c72a693cd9e508c4ef67a4023d5eed452148be58040a51d2bc1fcfbe549273b0a320aea45cf1614e5204a76",
          "sha256": "d1e90fbed9808a14b3b1662d35f193f940637e0b8074a2d2676167983c3c9cc6",
          "sha1": "969f91355074f2ab8c582ba530f28f58df3ea5dd",
          "md5": "fcc11aa90445f495b894f14bd9717ee7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-1.4.0-offline-javadoc.jar",
          "url": "permission_handler_android_release-1.4.0-offline-javadoc.jar",
          "size": 266789,
          "sha512": "89a83d19020d6ea8d7369b06a40d1d15a2a5a2ca2e2ac332f88ba0e0d09197765fc7d7eb12b44fa5a778629b796d6e0c197d913e8a30c1162ad0cdb648a08a00",
          "sha256": "086147659c484e1eec3a163e4a824fd0183d2189ad4750fc548ae8e3739c9ec0",
          "sha1": "91f2bd0047ffc970ed14fc2d67f5103c986cf429",
          "md5": "961238214999eabd80dd401416abffcb"
        }
      ]
    }
  ]
}
