{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.sensors",
    "module": "sensors_plus_release",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-1.5.3.aar",
          "url": "sensors_plus_release-1.5.3.aar",
          "size": 9122,
          "sha512": "7d88aebc67f36c5f9afe0740d29cf95a59a6ded6cffbf6058b32926b0fa0ff81dffa6c8564afb66d0ae592063571ed750274c98ca7e327113426c791eaa431d6",
          "sha256": "0fdd526d9552ca844c57d5a6ab5acc87bd5490ed3da58d85f76d4096271689bd",
          "sha1": "aea4bbd077915fbc8f54465d27e453d026589c1c",
          "md5": "756eeb6292bb82049c19b0a1bf4f4725"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-1.5.3.aar",
          "url": "sensors_plus_release-1.5.3.aar",
          "size": 9122,
          "sha512": "7d88aebc67f36c5f9afe0740d29cf95a59a6ded6cffbf6058b32926b0fa0ff81dffa6c8564afb66d0ae592063571ed750274c98ca7e327113426c791eaa431d6",
          "sha256": "0fdd526d9552ca844c57d5a6ab5acc87bd5490ed3da58d85f76d4096271689bd",
          "sha1": "aea4bbd077915fbc8f54465d27e453d026589c1c",
          "md5": "756eeb6292bb82049c19b0a1bf4f4725"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-1.5.3-sources.jar",
          "url": "sensors_plus_release-1.5.3-sources.jar",
          "size": 3078,
          "sha512": "ff8c14ac129b7e7d57ba1c1d48a7bd51656b3a77eccd557666bdf8a3b0172ecca0df5ba81b9ebbe8d029f941c22d8f18a241481915f11253f61492bda395d5e3",
          "sha256": "bc48e760fb87da67a364f00faddba3a1e477beac55f4ede297734f50cf1cd795",
          "sha1": "6b5cb27f9ac4f036dc8728014deb48440cb4dfba",
          "md5": "19db92f4ba177bdc11b351b78aa144de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-1.5.3-javadoc.jar",
          "url": "sensors_plus_release-1.5.3-javadoc.jar",
          "size": 264702,
          "sha512": "c465a63df4a74f760d52a28297b659c4f258b58dabc5a372efaa7590b1e4856bf1b8ec79acb84e8253c985fb5597c0ca372963fd286cc67f3d2aa5ddf5944fa1",
          "sha256": "a08955753ea57533180123d1e432595b69503786ae3dfb001f74631d397d3fa9",
          "sha1": "51000de5f464b8894dcc15f9f0b363187cff7539",
          "md5": "f139afa436fe80dbd2e1bae5300212cf"
        }
      ]
    }
  ]
}
