{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.7.1-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.1-sylvain-offline.aar",
          "url": "flutter_release-1.7.1-sylvain-offline.aar",
          "size": 7627485,
          "sha512": "3c54beabaceaa70e6bda115de3e4b027ffc104380d1c7e5020d55f9da567141f45c891c409c5c823c36e4eeb36f2784ae3336bfb00a0e83c232f170e164cf01a",
          "sha256": "79d614c1a12168384c454995fbd5e467d14c10a729ab29e9230b3f60f9bb79f0",
          "sha1": "1c5b8c7ab4ef1d5b4649663f3f16cf3ea46cca34",
          "md5": "a9cdd2f557beb79fea23ee739d0fbd95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.7.1-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.1-sylvain-offline.aar",
          "url": "flutter_release-1.7.1-sylvain-offline.aar",
          "size": 7627485,
          "sha512": "3c54beabaceaa70e6bda115de3e4b027ffc104380d1c7e5020d55f9da567141f45c891c409c5c823c36e4eeb36f2784ae3336bfb00a0e83c232f170e164cf01a",
          "sha256": "79d614c1a12168384c454995fbd5e467d14c10a729ab29e9230b3f60f9bb79f0",
          "sha1": "1c5b8c7ab4ef1d5b4649663f3f16cf3ea46cca34",
          "md5": "a9cdd2f557beb79fea23ee739d0fbd95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.7.1-sylvain-offline-sources.jar",
          "url": "flutter_release-1.7.1-sylvain-offline-sources.jar",
          "size": 1346,
          "sha512": "0be5b1cfc8fca51016624c3ed8c4017da1104abb75b51b7d84555d35a82d8260dcbc7b4c0a40408310c6659e59a89b1a17d916c1b13820974a067d07e510d802",
          "sha256": "c9ab4aeda76d2fbeab2a5f4f0dcd18100f7eb9d27af7a950c1e007cc67d994c7",
          "sha1": "5d245071ab3992565a50ba4c4201e8e12c47f688",
          "md5": "aa1e403425846d04e7208f5dcc9d4a0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.7.1-sylvain-offline-javadoc.jar",
          "url": "flutter_release-1.7.1-sylvain-offline-javadoc.jar",
          "size": 261644,
          "sha512": "99aaa35c7ec7e329bc30d28b7256043cdd43101a51847dec7525862a6d8cb1cc4ab0b70c93f8338d64d200f290c4125755a23e7d37e78a064180ffe54f65ad91",
          "sha256": "f9df0f7b70259f2ed7e9040dbdac48f41cb79ec3fb6d1d5d1140a10ea199fe1c",
          "sha1": "489d9290b56de06a0ae5ea879081bec057b3208d",
          "md5": "775e2e468402f2869169d72ada8ec7c6"
        }
      ]
    }
  ]
}
