{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.4.aar",
          "url": "flutter_release-1.3.4.aar",
          "size": 6884939,
          "sha512": "1409cb144362cfb65c0288aecb7371ed11a9446ca74517e9ac46edc9c70100a5dcf23f56e0aee5d6773c7d5c69ed0551b62a5ee31207d63b36a7bf36eae40af9",
          "sha256": "85b028d8d2d3acb1750e64ff6e34a13ee378f08307e023e960482a1fff7667b5",
          "sha1": "b5ec2d7e834aa194ff9e48a3c78294853c847ef3",
          "md5": "fa1c057df1143ed8cc51f2f5ae919a6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.3.4.aar",
          "url": "flutter_release-1.3.4.aar",
          "size": 6884939,
          "sha512": "1409cb144362cfb65c0288aecb7371ed11a9446ca74517e9ac46edc9c70100a5dcf23f56e0aee5d6773c7d5c69ed0551b62a5ee31207d63b36a7bf36eae40af9",
          "sha256": "85b028d8d2d3acb1750e64ff6e34a13ee378f08307e023e960482a1fff7667b5",
          "sha1": "b5ec2d7e834aa194ff9e48a3c78294853c847ef3",
          "md5": "fa1c057df1143ed8cc51f2f5ae919a6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.4-sources.jar",
          "url": "flutter_release-1.3.4-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.3.4-javadoc.jar",
          "url": "flutter_release-1.3.4-javadoc.jar",
          "size": 261619,
          "sha512": "005887950bf641996d6d4480a0d0c2128df2e3e38aab23d38bff85d590129abc2cd3f45e3f2f6a0c0a235a495aa55fcdd669b33eb7e3f39ea9efa82ca2a32222",
          "sha256": "d32069e1571f64ffc768aa5ffb07fed23978f5b7c2a1d464bd6c918e8d03791c",
          "sha1": "cc28f13fedaca473d71394b8455983d04adf8390",
          "md5": "3505d8d87b8c95d5e58c57e4931fa40d"
        }
      ]
    }
  ]
}
