{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.6-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.6-pearson-offline.aar",
          "url": "flutter_release-1.5.6-pearson-offline.aar",
          "size": 9126184,
          "sha512": "39f8f1a37f14451d9e32431b00b6796a5569028ff38e9bab1dcc32078ffae815d8973b8191fdc0e8154282fa3ebaace3936aed5483fb463fa79e9b34b559f71c",
          "sha256": "11034350d66a92f16cc1454112ba8a7c97efade542d9ded124c717370951da0c",
          "sha1": "09ef506b2057a234bf6a0dc6ff7a862a991cef3c",
          "md5": "73a81815c75bfc3e8187a8a8bcfef267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.6-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.6-pearson-offline.aar",
          "url": "flutter_release-1.5.6-pearson-offline.aar",
          "size": 9126184,
          "sha512": "39f8f1a37f14451d9e32431b00b6796a5569028ff38e9bab1dcc32078ffae815d8973b8191fdc0e8154282fa3ebaace3936aed5483fb463fa79e9b34b559f71c",
          "sha256": "11034350d66a92f16cc1454112ba8a7c97efade542d9ded124c717370951da0c",
          "sha1": "09ef506b2057a234bf6a0dc6ff7a862a991cef3c",
          "md5": "73a81815c75bfc3e8187a8a8bcfef267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.6-pearson-offline-sources.jar",
          "url": "flutter_release-1.5.6-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.6-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.5.6-pearson-offline-javadoc.jar",
          "size": 261644,
          "sha512": "55373af89fcfb2ac510d08dcf5e4331a03b15fc889908c8ccea4dacc795721be2044eb93645e3a5e5132965a59f4b50b744e7f2c7e9e69b2cd632eed0dc5b22f",
          "sha256": "34cbefdddc0a5c5c2418f5c5c69c2ac8343490e54962c83070b1e02ca1d97b58",
          "sha1": "3262a0863aa169093620c9ba36bba01a7bc198cf",
          "md5": "3e6ce3ba114c71850bfbdbdd4c7f35d9"
        }
      ]
    }
  ]
}
