{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.6.13-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.13-sylvain-offline.aar",
          "url": "flutter_release-1.6.13-sylvain-offline.aar",
          "size": 7624831,
          "sha512": "5c5d45a69c7eb1b75707fab588df119d5dfadf77378b152318f7f03ffa6b9f7725790855450dd8b376e805a05f9e42a961a1e3d9cbe02acf26ec20b8ca43642e",
          "sha256": "ea7fc8c0f92324541b2cd7d14b3b786998be30b97297428607663e59b1739a78",
          "sha1": "021c1383d7d449371da776017946012335404204",
          "md5": "863c5f66d8d23dc48e5ea65a03349fa9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.13-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.13-sylvain-offline.aar",
          "url": "flutter_release-1.6.13-sylvain-offline.aar",
          "size": 7624831,
          "sha512": "5c5d45a69c7eb1b75707fab588df119d5dfadf77378b152318f7f03ffa6b9f7725790855450dd8b376e805a05f9e42a961a1e3d9cbe02acf26ec20b8ca43642e",
          "sha256": "ea7fc8c0f92324541b2cd7d14b3b786998be30b97297428607663e59b1739a78",
          "sha1": "021c1383d7d449371da776017946012335404204",
          "md5": "863c5f66d8d23dc48e5ea65a03349fa9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.13-sylvain-offline-sources.jar",
          "url": "flutter_release-1.6.13-sylvain-offline-sources.jar",
          "size": 1346,
          "sha512": "0be5b1cfc8fca51016624c3ed8c4017da1104abb75b51b7d84555d35a82d8260dcbc7b4c0a40408310c6659e59a89b1a17d916c1b13820974a067d07e510d802",
          "sha256": "c9ab4aeda76d2fbeab2a5f4f0dcd18100f7eb9d27af7a950c1e007cc67d994c7",
          "sha1": "5d245071ab3992565a50ba4c4201e8e12c47f688",
          "md5": "aa1e403425846d04e7208f5dcc9d4a0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.13-sylvain-offline-javadoc.jar",
          "url": "flutter_release-1.6.13-sylvain-offline-javadoc.jar",
          "size": 261647,
          "sha512": "c0d71a241c6c478495757a7e5148b1e5bf36921e0299180ba21270dc1ec8b9f5bd316a4e5e22a57dd61f9fff6c996075a0bd2a9f9119b6a0c928ffe4f17afa25",
          "sha256": "e0bd09149f73eac4b6118cd02cbc44db8f20ccb0aae4f1c81359001f849c37e9",
          "sha1": "01bcb104f3b11d17f86c5887622e939690da7fe8",
          "md5": "2a13887b14c4ba25d6b64bcf3f504d89"
        }
      ]
    }
  ]
}
