{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.5-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.5-pearson-offline.aar",
          "url": "flutter_release-1.5.5-pearson-offline.aar",
          "size": 9126711,
          "sha512": "a6ae0ad189d83fa625a522c25f349eae12d99881423ef07882e4a692ff3918428739a5c33c290186d0660be6153788c059375745eaa0624b90abf202f00561c3",
          "sha256": "0147a615967e108f2f26abed246d16239541c984c656679483b6f0bba332e478",
          "sha1": "5cc0dbea7fb3a4c13c4786472da2897b0f3c537a",
          "md5": "f2d2048ab2c6d677e938b2cadb3072b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.5-pearson-offline.aar",
          "url": "flutter_release-1.5.5-pearson-offline.aar",
          "size": 9126711,
          "sha512": "a6ae0ad189d83fa625a522c25f349eae12d99881423ef07882e4a692ff3918428739a5c33c290186d0660be6153788c059375745eaa0624b90abf202f00561c3",
          "sha256": "0147a615967e108f2f26abed246d16239541c984c656679483b6f0bba332e478",
          "sha1": "5cc0dbea7fb3a4c13c4786472da2897b0f3c537a",
          "md5": "f2d2048ab2c6d677e938b2cadb3072b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.5-pearson-offline-sources.jar",
          "url": "flutter_release-1.5.5-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.5-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.5.5-pearson-offline-javadoc.jar",
          "size": 261642,
          "sha512": "f7756d1f2a9cd30605d970b39cca295298055ff11520adc19be80a6860b8fd846c2c22b87d8adc4d782a314aaf8fc5951c44752efe5b2971e879513127986cee",
          "sha256": "b534d1aceb32a7f32763f2e079b6b641a82bc88f8be0d5f7d64d08e4a39b887a",
          "sha1": "d7a108481245ef9243adaad214d50048dc500987",
          "md5": "4be358029376e8e19121174b88980afb"
        }
      ]
    }
  ]
}
