{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
    "module": "palmid_sdk_flutter_android_veinshine_release",
    "version": "1.6.15-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline.aar",
          "size": 16369454,
          "sha512": "98c30c7921688efc056a85ab6b37112b8e172b50090074a37523c9be28f94c0543d62a5142a8a5cae2e6e7ef8f6b142b1b7df7463106d291072df30b32cd7781",
          "sha256": "4e61e0cb5755c961bdd6a26762be781b7b6a90ced8e9d0975e2b23aa2be195f0",
          "sha1": "b7bb02369b878185ae228fec486f7609a649abec",
          "md5": "c2a79437d085521d6c7f92f403ac01d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline.aar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline.aar",
          "size": 16369454,
          "sha512": "98c30c7921688efc056a85ab6b37112b8e172b50090074a37523c9be28f94c0543d62a5142a8a5cae2e6e7ef8f6b142b1b7df7463106d291072df30b32cd7781",
          "sha256": "4e61e0cb5755c961bdd6a26762be781b7b6a90ced8e9d0975e2b23aa2be195f0",
          "sha1": "b7bb02369b878185ae228fec486f7609a649abec",
          "md5": "c2a79437d085521d6c7f92f403ac01d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline-sources.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline-sources.jar",
          "size": 67444,
          "sha512": "6ab41afd79e3a6dd9d7533527918ad586b6a1aa9c02f7e56c14b82aad5669a6beda5de3db5dcc4345828623cc0600e664d8e9238bb3be3849aba5dd8f1a20bab",
          "sha256": "390f77b886277206070d69a7bc5423f12a43ef4a06dd491f8dbd7aa5b49657d6",
          "sha1": "bcce358c11d03c706e6a1ae5188c6257cb753a4c",
          "md5": "8ef0d13929c36d8a27f65f4d562d2904"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_android_veinshine_release-1.6.15-sylvain-offline-javadoc.jar",
          "size": 583120,
          "sha512": "bddfab671000b3dec0b95ae9613a529bf82ae6877ba88c640bc4104f9647f91a3aaa8df23d65c10eb6467bb27ba46a3a575a77d2903666734fc3949354edb058",
          "sha256": "b21d9ca370ce50fa87f8d89eacb5ff8f97819caae4d74b907c1feda364b9927e",
          "sha1": "8cc9b37eac861da4a19c8be9561df2ff677363c1",
          "md5": "17f88b040bd88186effd4c841aa6e675"
        }
      ]
    }
  ]
}
