{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.5-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.5-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.5-pearson-offline.aar",
          "size": 34870986,
          "sha512": "8594e80286c4ef32c01957292c92edac41e707b364a4965755ec6f58f32ac4f91abdeac74054e94474e31f4b606941d4fccd805fc3fb2995250a05328c6bccad",
          "sha256": "76220dc1adf48cc3ca12adea31b13cd7c70d3d41cdeeda53bcd450219aef14a8",
          "sha1": "f7ce8c2e378af44a219643e3361c9a01c8aae4c3",
          "md5": "c1fed7f7bcba76a1039c1b72c86989ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.5-pearson-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.5-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.5-pearson-offline.aar",
          "size": 34870986,
          "sha512": "8594e80286c4ef32c01957292c92edac41e707b364a4965755ec6f58f32ac4f91abdeac74054e94474e31f4b606941d4fccd805fc3fb2995250a05328c6bccad",
          "sha256": "76220dc1adf48cc3ca12adea31b13cd7c70d3d41cdeeda53bcd450219aef14a8",
          "sha1": "f7ce8c2e378af44a219643e3361c9a01c8aae4c3",
          "md5": "c1fed7f7bcba76a1039c1b72c86989ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.5-pearson-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.5-pearson-offline-sources.jar",
          "size": 17149,
          "sha512": "c097e9f9245cb64921f3c62f487b469ff0367e13d8122f72aa90d9deafcc4977899884bcba37afa25aef0b771434cebc43f59f5b9f439aa0bbb3e428cc3d107a",
          "sha256": "b601253edc8ea544603e33119650b38e8264a53ac3ff240718a81b92c5e08081",
          "sha1": "fd57504702462da7d451ad9181c7ad3df5f330cf",
          "md5": "b4356bd794cdbc5a358a67e0f2e4436e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.5-pearson-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.5-pearson-offline-javadoc.jar",
          "size": 423527,
          "sha512": "1d472387c4e97078afb3ca9958de0a4640e7e27a9abc57a3707862817865a7c58a0d7b6703f73c53600cd809566d6d0129786f04bf7385031335ae961ebce5b7",
          "sha256": "7f3cbe6e6162a904b76518f9301c6f8cfb76978d6363971fdab191ba0c2468bd",
          "sha1": "81fcaf354d45bfa7f6a54b5bf55c679d6d7ebc6f",
          "md5": "f06a05ce30bf2273b61f7f93511cb9cf"
        }
      ]
    }
  ]
}
