{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.5.2-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.2-pearson-offline.aar",
          "url": "flutter_release-1.5.2-pearson-offline.aar",
          "size": 10188796,
          "sha512": "c3016aaac5dbab15ff4ef9b1c92ec9e636cf543a62979c781845670cecd6a92b7204cfb2441e845c19fc7fba61ba4f6e5ce7146dafeccfcc254dd0d026f7fc0d",
          "sha256": "c029755d00a551ac23dc707f04262bfd212f941134225081f1ecc33cc5731edc",
          "sha1": "94da9f7a0592d465500e4366ac8dfba99dfa0522",
          "md5": "2bdc4c366f4d700a8b629e9cd99b9e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "1.5.2-pearson-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.5.2-pearson-offline.aar",
          "url": "flutter_release-1.5.2-pearson-offline.aar",
          "size": 10188796,
          "sha512": "c3016aaac5dbab15ff4ef9b1c92ec9e636cf543a62979c781845670cecd6a92b7204cfb2441e845c19fc7fba61ba4f6e5ce7146dafeccfcc254dd0d026f7fc0d",
          "sha256": "c029755d00a551ac23dc707f04262bfd212f941134225081f1ecc33cc5731edc",
          "sha1": "94da9f7a0592d465500e4366ac8dfba99dfa0522",
          "md5": "2bdc4c366f4d700a8b629e9cd99b9e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.2-pearson-offline-sources.jar",
          "url": "flutter_release-1.5.2-pearson-offline-sources.jar",
          "size": 1219,
          "sha512": "5dee25b2aaf8dd852f009feb36187a3759faf128cef3bb98bd4cb6353b97f1493d9954af3006c16650d10ca58e43308da6e20799f2fc381af0e8cf58cf4d3a41",
          "sha256": "38b843154ac91d10ebc426b265cf95494cd72589a6e532730f568493ce841c9d",
          "sha1": "8232cb128221060e4c74e0cfa3708bb69a29ceab",
          "md5": "7aef2f0609c7f2b1b87614b5ab2d4721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.5.2-pearson-offline-javadoc.jar",
          "url": "flutter_release-1.5.2-pearson-offline-javadoc.jar",
          "size": 261642,
          "sha512": "35dacc60d8dcd37b2eb3622539edf06f69e701beddf167723e5f4b06c40c6b2a9cac6753b0ac825da245b75153ca9b26bda284e6a8651262d1bdf4ff74787896",
          "sha256": "5b1b52fe59e1b2c5d23af1fa5c1fc25695d2bffbe4da158afc62b1ae5484adcf",
          "sha1": "c97ca3b5e9ed3348a0e1b6eb316955bf040ff593",
          "md5": "75f5a3b8567e15c8f713f66592bc4073"
        }
      ]
    }
  ]
}
