{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.0.aar",
          "url": "palmid_sdk_flutter_release-1.5.0.aar",
          "size": 34727778,
          "sha512": "e040fd36cf157d03ce08b98ee0a7689fe0e88aa790e494efb583b2b43b150d056ac38424c7de261ea8b3c78e80bebbec0a1e5cfd4e9811c0b57ed8b90d8a4dee",
          "sha256": "1252ff11317b181ab1c0417ef2f7ccdcd6b6cdaa9f4d7b9242d6ef452c909ce6",
          "sha1": "bb0c92cacc37ba8e3f7e5adbe07fd8d1d88c43f6",
          "md5": "bf407743d64eeefef4059a6b039c927a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.0.aar",
          "url": "palmid_sdk_flutter_release-1.5.0.aar",
          "size": 34727778,
          "sha512": "e040fd36cf157d03ce08b98ee0a7689fe0e88aa790e494efb583b2b43b150d056ac38424c7de261ea8b3c78e80bebbec0a1e5cfd4e9811c0b57ed8b90d8a4dee",
          "sha256": "1252ff11317b181ab1c0417ef2f7ccdcd6b6cdaa9f4d7b9242d6ef452c909ce6",
          "sha1": "bb0c92cacc37ba8e3f7e5adbe07fd8d1d88c43f6",
          "md5": "bf407743d64eeefef4059a6b039c927a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.0-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.0-sources.jar",
          "size": 17149,
          "sha512": "c097e9f9245cb64921f3c62f487b469ff0367e13d8122f72aa90d9deafcc4977899884bcba37afa25aef0b771434cebc43f59f5b9f439aa0bbb3e428cc3d107a",
          "sha256": "b601253edc8ea544603e33119650b38e8264a53ac3ff240718a81b92c5e08081",
          "sha1": "fd57504702462da7d451ad9181c7ad3df5f330cf",
          "md5": "b4356bd794cdbc5a358a67e0f2e4436e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.0-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.0-javadoc.jar",
          "size": 423072,
          "sha512": "057fc21d63b121f66512048bfc60d7a17bdfb58e4e0cde59be0fc9a3ee5bfd558f5d044ee2f77460cbbc15a62bd09130de77a6e43caad3f4bb73c509eedbd6a2",
          "sha256": "d6e6df4a8cca23fa03c7c8b1090808390e929783d453aa65530b3d593eab34f7",
          "sha1": "47d614a4f6bcbe8c0be5514c5351a215995b5dc8",
          "md5": "6a9755e92e97f5657ff3398d36e575c7"
        }
      ]
    }
  ]
}
