{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0.aar",
          "url": "palmid_sdk_flutter_release-1.8.0.aar",
          "size": 35429621,
          "sha512": "9dfd16d4b56502d2d8cc4f3a4f5fdaab56bccd4a30841686b08aec28d3513070804351306de636bd4596fd27c14102e8bfd4a5b579b8676a8de3d265bbf58988",
          "sha256": "fc301e5a23eaf05c9187a9b885b7dc702bb409b3f998055b3aeecf26530a0268",
          "sha1": "9cc276b910a52088ee488156d7993a201789d4d8",
          "md5": "1e15b9ae71ebdc8014c47bf584b8f2e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0.aar",
          "url": "palmid_sdk_flutter_release-1.8.0.aar",
          "size": 35429621,
          "sha512": "9dfd16d4b56502d2d8cc4f3a4f5fdaab56bccd4a30841686b08aec28d3513070804351306de636bd4596fd27c14102e8bfd4a5b579b8676a8de3d265bbf58988",
          "sha256": "fc301e5a23eaf05c9187a9b885b7dc702bb409b3f998055b3aeecf26530a0268",
          "sha1": "9cc276b910a52088ee488156d7993a201789d4d8",
          "md5": "1e15b9ae71ebdc8014c47bf584b8f2e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-sources.jar",
          "url": "palmid_sdk_flutter_release-1.8.0-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.8.0-javadoc.jar",
          "size": 423171,
          "sha512": "f6d7697e4b424dedd9a722e5fa4fcb80cca8883bd3747135f29bc708444449c768638aab7517297f41370a69163b2f0e5a4ee108840d6a96e7753cbb676a2e96",
          "sha256": "5d5a503cd9cc212b89099249875cfb85d68629c188078e2ffa21a87e5be7f6ba",
          "sha1": "095f4c8a3523d4c4108f1ef7ff8c7e8b68cd3ebf",
          "md5": "256b23c1f0494fa80341dce50e8bed02"
        }
      ]
    }
  ]
}
