{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid",
    "module": "native_sdk",
    "version": "1.3.6-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.3.6-offline.aar",
          "url": "native_sdk-1.3.6-offline.aar",
          "size": 56519,
          "sha512": "2db79722065f7630ca7016bdb3ee0e056c94bac626c491d8db7c580b4df4f6a7c17733c094a36d0ee35e57ec04a9ab9ba392800c6713f4072985b9b8f067c73a",
          "sha256": "da43f0e336ce273176f91ae7f01d44172a327e1fee0a498367a62b195e2639b5",
          "sha1": "f4abbf497cbbf1945098f64e0b4c1ac7a597c0b9",
          "md5": "23841a697f47c59e0f0cc9789ae85639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.3.6-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.3.6-offline.aar",
          "url": "native_sdk-1.3.6-offline.aar",
          "size": 56519,
          "sha512": "2db79722065f7630ca7016bdb3ee0e056c94bac626c491d8db7c580b4df4f6a7c17733c094a36d0ee35e57ec04a9ab9ba392800c6713f4072985b9b8f067c73a",
          "sha256": "da43f0e336ce273176f91ae7f01d44172a327e1fee0a498367a62b195e2639b5",
          "sha1": "f4abbf497cbbf1945098f64e0b4c1ac7a597c0b9",
          "md5": "23841a697f47c59e0f0cc9789ae85639"
        }
      ]
    }
  ]
}
