{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.1-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-offline.aar",
          "size": 34870987,
          "sha512": "d1f33d7faaa850c0ceb1c06ddc552da425e755fc76ff91e2aabe0ee276e92c385ba96605a52210a6280514d2c6cba8942954d6bfdc807089570fd3e5ac5ba3eb",
          "sha256": "fdd2fabc7a6c1e33074fbcbf3a0b7c1b62d01067b6430e6bf487a0bf9dab88ad",
          "sha1": "958d2f2678cfffc78c4603cf2951899312eefda8",
          "md5": "e001aa9f585f8b023b1a03cdd7596cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.1-pearson-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-offline.aar",
          "size": 34870987,
          "sha512": "d1f33d7faaa850c0ceb1c06ddc552da425e755fc76ff91e2aabe0ee276e92c385ba96605a52210a6280514d2c6cba8942954d6bfdc807089570fd3e5ac5ba3eb",
          "sha256": "fdd2fabc7a6c1e33074fbcbf3a0b7c1b62d01067b6430e6bf487a0bf9dab88ad",
          "sha1": "958d2f2678cfffc78c4603cf2951899312eefda8",
          "md5": "e001aa9f585f8b023b1a03cdd7596cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-offline-sources.jar",
          "size": 17149,
          "sha512": "c097e9f9245cb64921f3c62f487b469ff0367e13d8122f72aa90d9deafcc4977899884bcba37afa25aef0b771434cebc43f59f5b9f439aa0bbb3e428cc3d107a",
          "sha256": "b601253edc8ea544603e33119650b38e8264a53ac3ff240718a81b92c5e08081",
          "sha1": "fd57504702462da7d451ad9181c7ad3df5f330cf",
          "md5": "b4356bd794cdbc5a358a67e0f2e4436e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.1-pearson-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.1-pearson-offline-javadoc.jar",
          "size": 423525,
          "sha512": "07b9b1e04e9e30b96e30d40e17c61336b2841f3242ec7225e2018611103e75e852670ffeab78a5f98ac8efb15dddad1bd845c1c6d6041aa0b022c0abba981957",
          "sha256": "573c300d18c955d5f3c39aa323081f0fafc591ee05ae8eae0e1723948d68b4bf",
          "sha1": "aa46332318bda58ca7281e707b44dde45dbf0c05",
          "md5": "369c369b49cb80ac23a7b9ce0a50e1bb"
        }
      ]
    }
  ]
}
