{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.7.0-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.7.0-offline.aar",
          "url": "device_info_plus_release-1.7.0-offline.aar",
          "size": 7083,
          "sha512": "f349fdc987a8641ee13554a1e8ac41d2d8379936220e3f44e598c58f5a9a25f8c9ee7ed5d7f393781a9dce6bcccda0a364b533c4033010dea5c055f41fb58d68",
          "sha256": "50e7fc2a2935ac9ed07df315674b2d335b0da6fe588a5bd7ec48639fb803a0aa",
          "sha1": "aa26b47f69f94f5048429e356616862269cb11a8",
          "md5": "0d83bfd016b100cb0cba25f523169841"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.7.0-offline.aar",
          "url": "device_info_plus_release-1.7.0-offline.aar",
          "size": 7083,
          "sha512": "f349fdc987a8641ee13554a1e8ac41d2d8379936220e3f44e598c58f5a9a25f8c9ee7ed5d7f393781a9dce6bcccda0a364b533c4033010dea5c055f41fb58d68",
          "sha256": "50e7fc2a2935ac9ed07df315674b2d335b0da6fe588a5bd7ec48639fb803a0aa",
          "sha1": "aa26b47f69f94f5048429e356616862269cb11a8",
          "md5": "0d83bfd016b100cb0cba25f523169841"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.7.0-offline-sources.jar",
          "url": "device_info_plus_release-1.7.0-offline-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.7.0-offline-javadoc.jar",
          "url": "device_info_plus_release-1.7.0-offline-javadoc.jar",
          "size": 260838,
          "sha512": "d98d3015adb8925404c1c6e7c597aa81215dce9bdd5a04516be787021c94edc4b48cc0f18a5573320a5a5fed1b4469955b5a1ea566aa0682ce92a7a436fd4b75",
          "sha256": "392b0f6a86099b9fcb10bdd7762c3891d7f0c04b61108305061405bedee8fdc2",
          "sha1": "582f352b4fe07e51eb8827338163290a93109b1e",
          "md5": "a4d7d92f0a8ec0862549e81212af0e63"
        }
      ]
    }
  ]
}
