{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.8.0-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.8.0-pearson-offline.aar",
          "size": 35429471,
          "sha512": "e434e6aec07b920ec55ded54ccf7740b11e9a44a0af42db7f074480e7dee285c7e9e86669b772fe405080773ece54b1ee67e2c375f267da3288cfe566fd1449f",
          "sha256": "fc110bb4c0a52ea91322cbdc33ee4a0416dc413096743bd062fb61b552953ef1",
          "sha1": "5090d1cfc8de7a7bfd3ecb291360af64c25e5083",
          "md5": "9faff81b8c2c2ec8b7e848bdf8c9b49d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0-pearson-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.8.0-pearson-offline.aar",
          "size": 35429471,
          "sha512": "e434e6aec07b920ec55ded54ccf7740b11e9a44a0af42db7f074480e7dee285c7e9e86669b772fe405080773ece54b1ee67e2c375f267da3288cfe566fd1449f",
          "sha256": "fc110bb4c0a52ea91322cbdc33ee4a0416dc413096743bd062fb61b552953ef1",
          "sha1": "5090d1cfc8de7a7bfd3ecb291360af64c25e5083",
          "md5": "9faff81b8c2c2ec8b7e848bdf8c9b49d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-pearson-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.8.0-pearson-offline-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.8.0-pearson-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.8.0-pearson-offline-javadoc.jar",
          "size": 423622,
          "sha512": "f62794a3e9e5dd95a5005dd9807730326ef104f4dfbd48d3dc589bf6bdd7509be62903d5c03573d68fcd00d4be4de4dc3226f2f31c10d86d20933ef04256bed7",
          "sha256": "c1799a859102dcb725ca60fde23568058877a983fee5da63fdeeae681b96d075",
          "sha1": "93a9f843e6a7625880653c4a729dc0e8f6eb42b6",
          "md5": "fd8f40e4d2b521564b012c73cc2da587"
        }
      ]
    }
  ]
}
