{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.8.0-mainmoney",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0-mainmoney.aar",
          "url": "flutter_release-1.8.0-mainmoney.aar",
          "size": 8015652,
          "sha512": "abab2ad52b7a04a42df9eb2e4bd68a5550c307de2f8daaf4866eeb7cbedb107d2d6e3e89c80f3504340ae94f61577a7dd86e40e0327c7a23eb5d58b594c95c91",
          "sha256": "eb0a00add311f21332b1b2e288a534db10fbf629a6703c8fdcaf94bb307a4d88",
          "sha1": "e46b8966ebf007cb9b96a8a98957778c96e5e028",
          "md5": "1e4c56245449088265a77deea8e86383"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        },
        {
          "group": "com.palmid.palmid_sdk_flutter",
          "module": "palmid_sdk_flutter_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.8.0-mainmoney"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0-mainmoney.aar",
          "url": "flutter_release-1.8.0-mainmoney.aar",
          "size": 8015652,
          "sha512": "abab2ad52b7a04a42df9eb2e4bd68a5550c307de2f8daaf4866eeb7cbedb107d2d6e3e89c80f3504340ae94f61577a7dd86e40e0327c7a23eb5d58b594c95c91",
          "sha256": "eb0a00add311f21332b1b2e288a534db10fbf629a6703c8fdcaf94bb307a4d88",
          "sha1": "e46b8966ebf007cb9b96a8a98957778c96e5e028",
          "md5": "1e4c56245449088265a77deea8e86383"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.8.0-mainmoney-sources.jar",
          "url": "flutter_release-1.8.0-mainmoney-sources.jar",
          "size": 1197,
          "sha512": "13af0260069b10229f99622f0cd22873d143cd97879092b96391366c94c98cd9919e3d939e0d1af2da3f3c81086903d276546eaf97c92f67b7adbb040fa9718f",
          "sha256": "cf6994093f2e397b7c3404d5b363748790b42bf75ca5c7a18ae7593ed025503a",
          "sha1": "ce9643c1428d35b1451cdf51c283aa6bae54248a",
          "md5": "131e59e4a103a174cd813de4f80428c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.8.0-mainmoney-javadoc.jar",
          "url": "flutter_release-1.8.0-mainmoney-javadoc.jar",
          "size": 261635,
          "sha512": "7da25336d9ab5ba75e6594d21aeab934fbbbb38b3d3713c55610bb41b5a07d187d7018c55dff3d67f0bb5cbb9344f8171e72220b617d011e48f2f7a89587a23a",
          "sha256": "66c724eab4c746a734c65a724d078039a9946b91bc8eb497d0b49174000ffc26",
          "sha1": "b1bcd05ceab25456ec8a409c2905c30a33a10226",
          "md5": "267efe9459eec49a5f7e2135727505a9"
        }
      ]
    }
  ]
}
