{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.6.14-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.14-sylvain-offline.aar",
          "url": "flutter_release-1.6.14-sylvain-offline.aar",
          "size": 7624840,
          "sha512": "8878a20e97f51744c38eae39998cfcc8a03ca2a0ecba8d9cf86c84535a996ade80bd8d95122d085141c5c814e0ae9e81fffd97fc49375a0198da714b2c31e5b2",
          "sha256": "74461f0dccb9122d5414b41eb2ad50c5f63523fd3486bdecf0c5a7e2c7fc370d",
          "sha1": "9bde547fdd2b508cda65a1af5c9d4470d6382be3",
          "md5": "cfb3969a35a885fb19d1eb8cca426872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_barcode_scanning",
          "module": "google_mlkit_barcode_scanning_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.14-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.14-sylvain-offline.aar",
          "url": "flutter_release-1.6.14-sylvain-offline.aar",
          "size": 7624840,
          "sha512": "8878a20e97f51744c38eae39998cfcc8a03ca2a0ecba8d9cf86c84535a996ade80bd8d95122d085141c5c814e0ae9e81fffd97fc49375a0198da714b2c31e5b2",
          "sha256": "74461f0dccb9122d5414b41eb2ad50c5f63523fd3486bdecf0c5a7e2c7fc370d",
          "sha1": "9bde547fdd2b508cda65a1af5c9d4470d6382be3",
          "md5": "cfb3969a35a885fb19d1eb8cca426872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.14-sylvain-offline-sources.jar",
          "url": "flutter_release-1.6.14-sylvain-offline-sources.jar",
          "size": 1346,
          "sha512": "0be5b1cfc8fca51016624c3ed8c4017da1104abb75b51b7d84555d35a82d8260dcbc7b4c0a40408310c6659e59a89b1a17d916c1b13820974a067d07e510d802",
          "sha256": "c9ab4aeda76d2fbeab2a5f4f0dcd18100f7eb9d27af7a950c1e007cc67d994c7",
          "sha1": "5d245071ab3992565a50ba4c4201e8e12c47f688",
          "md5": "aa1e403425846d04e7208f5dcc9d4a0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.14-sylvain-offline-javadoc.jar",
          "url": "flutter_release-1.6.14-sylvain-offline-javadoc.jar",
          "size": 261648,
          "sha512": "6d8567b92d72fcebdd7d6a5a69326d494a1c93cd221e6c8645b4daca4786a1e6f19811875ab60f3eca0c897c523d33485b023c4b22948f7c9a62395f4a462154",
          "sha256": "7dc4f6b314fede2f125a721b5c2a638e9f8bccb14bae755635070c5699ce5c8e",
          "sha1": "74082544c2c599094c8c8cf11064ee7f195d92e0",
          "md5": "a41d6a69131a3dd4fc6f94ff4e6a8829"
        }
      ]
    }
  ]
}
