{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.5.7-pearson-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.7-pearson-offline.aar",
          "size": 34871492,
          "sha512": "a09a894123b29f19211699a10e943a850ad2da9174b47a49e6657924b6cc302a724e31afc837c3f982c1bb7dd13420746f6f41cfb889c048b11b945522a9355c",
          "sha256": "12787f43376c2038266acb4a76b5bd04643a5627662fd55d1f2d4d8712cbd177",
          "sha1": "ba87cc2ac0b0d9d271ef8380ca91fbf51fec8fb5",
          "md5": "e07cb000b462f0e8482dc26a38431050"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.5.7-pearson-offline"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-pearson-offline.aar",
          "url": "palmid_sdk_flutter_release-1.5.7-pearson-offline.aar",
          "size": 34871492,
          "sha512": "a09a894123b29f19211699a10e943a850ad2da9174b47a49e6657924b6cc302a724e31afc837c3f982c1bb7dd13420746f6f41cfb889c048b11b945522a9355c",
          "sha256": "12787f43376c2038266acb4a76b5bd04643a5627662fd55d1f2d4d8712cbd177",
          "sha1": "ba87cc2ac0b0d9d271ef8380ca91fbf51fec8fb5",
          "md5": "e07cb000b462f0e8482dc26a38431050"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-pearson-offline-sources.jar",
          "url": "palmid_sdk_flutter_release-1.5.7-pearson-offline-sources.jar",
          "size": 17378,
          "sha512": "2b0617dbaaa45fcce8d020838e698258303a63a167e2e03f1e544cb6b1a7847061692381d92d5b9531174ac0c37069ebaf7cf333ad661b936ce42a150bbd86ba",
          "sha256": "31f785cb274816be5168c3b8694dba9f438db15d1a81c8e862953511630fe1fe",
          "sha1": "c5944e1b72224f20eaa6438ca1eaf5d68742dc44",
          "md5": "9d78434bbcead944a27461a3fd94aab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.5.7-pearson-offline-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.5.7-pearson-offline-javadoc.jar",
          "size": 423548,
          "sha512": "b0d917e0ed48b7ccab7c1807773d83767c51c933bf4bbc9c2d9c6ad827d0daac720a69caa2093f73577c9766d10436aa699c57844fed33a97720a8cf543c19c5",
          "sha256": "ed80d31137cc5567cd5c26d62d69c6349db1a8ff97c9fdd5710bd6f382aebd03",
          "sha1": "37570fc0c2d6ccfbab054deff612c8df1209dc30",
          "md5": "3f58990dfffe42f07c352b3830f32be1"
        }
      ]
    }
  ]
}
