{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid.embed_app",
    "module": "flutter_release",
    "version": "1.6.6-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.6-sylvain-offline.aar",
          "url": "flutter_release-1.6.6-sylvain-offline.aar",
          "size": 7492130,
          "sha512": "59594853c24f492536310235148f3224b0a42d8ef0551e09ff423ea007120ef4b2f8e47fa7e1ae03ecf06a9b1549681cb588f6d560e9ad2b05e2038208cc95e6",
          "sha256": "55a44f3eb5ee3babaf767050e55741fb3ade9279dc881efb9975f9610e0300be",
          "sha1": "a6c51c2f1b8cddbdea61b87a00dd8c39ec5634a8",
          "md5": "fd93da25d83b714ea763d5d1c62ceb08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "com.redrockbiometrics.palmid_sdk_flutter_android_veinshine",
          "module": "palmid_sdk_flutter_android_veinshine_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.6.6-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.6-sylvain-offline.aar",
          "url": "flutter_release-1.6.6-sylvain-offline.aar",
          "size": 7492130,
          "sha512": "59594853c24f492536310235148f3224b0a42d8ef0551e09ff423ea007120ef4b2f8e47fa7e1ae03ecf06a9b1549681cb588f6d560e9ad2b05e2038208cc95e6",
          "sha256": "55a44f3eb5ee3babaf767050e55741fb3ade9279dc881efb9975f9610e0300be",
          "sha1": "a6c51c2f1b8cddbdea61b87a00dd8c39ec5634a8",
          "md5": "fd93da25d83b714ea763d5d1c62ceb08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.6-sylvain-offline-sources.jar",
          "url": "flutter_release-1.6.6-sylvain-offline-sources.jar",
          "size": 1275,
          "sha512": "516f87dd6a5f41d10cae19ec553a649d2d182948fa4abfe6cf3a6763e855478584ca0fafbc4d4f132e4db37daf10c4d50104a830bc6c9b52ef47b9e97e8b9d61",
          "sha256": "be211fcf47bd81e9c5d420622afc1edc0cc2fc57c5bee2db8b97a4d15ab6293a",
          "sha1": "edd41270e4541655faf517a8c892d859da0aa8d7",
          "md5": "0e5704b9e4fb4eec7d3557895b3be597"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.6.6-sylvain-offline-javadoc.jar",
          "url": "flutter_release-1.6.6-sylvain-offline-javadoc.jar",
          "size": 261646,
          "sha512": "864c52b8c12f8a59960c386fd217d6457ab3450fa76cc34279265077bd50dad25f3b51c80013b9dd79e6978a6c86ced423584cc47f1a2a95a432a6ed20c92206",
          "sha256": "dce58cbcffc866b982e78be6cbb79e61fb158c1a977843dff4c87a0e76f9b1e4",
          "sha1": "60f3758aefa9494bc3b072532a41fd3282c6f800",
          "md5": "52c35a8b4d7e8d5706c41c22a89ffc39"
        }
      ]
    }
  ]
}
