{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_commons",
    "module": "google_mlkit_commons_release",
    "version": "1.7.1-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-1.7.1-sylvain-offline.aar",
          "url": "google_mlkit_commons_release-1.7.1-sylvain-offline.aar",
          "size": 7616,
          "sha512": "2bfd9dce335a16f15c291b411f5ed802973bc678ded29873450a5ded1b967b5bc335a9797f2df39bbd8bea4d09d5107d2de508ee627a437660f2d039c61b9852",
          "sha256": "36991bff001d425f887db4de2e4b3de23d789c08602035bd5b93fe405ef60860",
          "sha1": "7fedc4fac6f69f9eeb2c59d636ee0e1fbb355998",
          "md5": "107f163e2155b84c0d420fc5248cc8f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-1.7.1-sylvain-offline.aar",
          "url": "google_mlkit_commons_release-1.7.1-sylvain-offline.aar",
          "size": 7616,
          "sha512": "2bfd9dce335a16f15c291b411f5ed802973bc678ded29873450a5ded1b967b5bc335a9797f2df39bbd8bea4d09d5107d2de508ee627a437660f2d039c61b9852",
          "sha256": "36991bff001d425f887db4de2e4b3de23d789c08602035bd5b93fe405ef60860",
          "sha1": "7fedc4fac6f69f9eeb2c59d636ee0e1fbb355998",
          "md5": "107f163e2155b84c0d420fc5248cc8f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-1.7.1-sylvain-offline-sources.jar",
          "url": "google_mlkit_commons_release-1.7.1-sylvain-offline-sources.jar",
          "size": 4013,
          "sha512": "56cca6fb77e2d4f711c4c6a5e0e45565d0fcb88e03f1f1e6df13c5312aefff10536363f763baae973d8ea6b2c49ee854beca5db1a81554c47054a5485f1cf4a1",
          "sha256": "3ca1b9714fb47373196cdb49274585ce5c7b0e2a728871bd7bbfea1a60d1eb58",
          "sha1": "545a66c10a2570b10e14665a973a6e4aac4f21a1",
          "md5": "b05d999a79a724354332f75223d40763"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-1.7.1-sylvain-offline-javadoc.jar",
          "url": "google_mlkit_commons_release-1.7.1-sylvain-offline-javadoc.jar",
          "size": 273190,
          "sha512": "78dc806a16b9653ce377219246a0289023aacdf572d81f5407079a015e6cf17b3f20bad1738f6587ebefee1d479a5615c7af1a8f12fcb5f0fc0376344c7c67d6",
          "sha256": "8803692cbd5864b18e3694725f94d11485b88d18b3eefc1515930cd2a0b6f29a",
          "sha1": "df917a42b30445f325a65b32dbe9ce1cf2a5f76e",
          "md5": "42ae4a8bacd09a66e4c50e59dd0bdfc1"
        }
      ]
    }
  ]
}
