{
  "formatVersion": "1.1",
  "component": {
    "group": "com.palmid",
    "module": "native_sdk",
    "version": "1.6.15-sylvain-offline",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.6.15-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.6.15-sylvain-offline.aar",
          "url": "native_sdk-1.6.15-sylvain-offline.aar",
          "size": 13310,
          "sha512": "7708e06788536a4ed5aada3d57c57e5f34e0528ceed9fc466ed4672b42f5f46cb684dde25b8550668c35bd0d035a1d038e474471ceab0d51dc37f6395c1b5cff",
          "sha256": "0961c59527389a4aefb7b66104a9e525fe7a2c437d261bf8968fb2440d019fd8",
          "sha1": "820a39f1b3d386558970e0baaf7306bca433d435",
          "md5": "2e6c9ac2293aea668f0483e38e994c60"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.palmid.embed_app",
          "module": "flutter_release",
          "version": {
            "requires": "1.6.15-sylvain-offline"
          }
        }
      ],
      "files": [
        {
          "name": "native_sdk-1.6.15-sylvain-offline.aar",
          "url": "native_sdk-1.6.15-sylvain-offline.aar",
          "size": 13310,
          "sha512": "7708e06788536a4ed5aada3d57c57e5f34e0528ceed9fc466ed4672b42f5f46cb684dde25b8550668c35bd0d035a1d038e474471ceab0d51dc37f6395c1b5cff",
          "sha256": "0961c59527389a4aefb7b66104a9e525fe7a2c437d261bf8968fb2440d019fd8",
          "sha1": "820a39f1b3d386558970e0baaf7306bca433d435",
          "md5": "2e6c9ac2293aea668f0483e38e994c60"
        }
      ]
    }
  ]
}
